### ISSUE TITLE
新版weexpack报错

### ISSUE THREAD

**Issue by Jam1zhu** [weexteam/weex-pack#100]
升级weexpack@0.3.11，创建新项目后，使用weexpack指令
```bash
weexpack platform list
```
会报错
```bash
Error: Unexpected token <<
```

**Comment by xblibo** [comment]
node_modules/weexpack/lib/src/cordova/platform.js:418   他们这个文件merge有问题
看这个 https://github.com/weexteam/weex-pack/issues/101
把这个文件中 418, 422, 424 这几行删掉

**Comment by exolution** [comment]
已修复
