### ISSUE TITLE
platfrom.js 你们这个文件merge疵, 也敢release

### ISSUE THREAD

**Issue by xblibo** [weexteam/weex-pack#101]
node_modules/weexpack/lib/src/cordova/platform.js:418

.then(function() {
            <<<<<<< HEAD
            events.emit('log', 'Remove platform ' + targets + ' success');
            return hooksRunner.fire('after_platform_rm', opts);

            =======
            return hooksRunner.fire('after_platform_rm', opts);
            >>>>>>> dev
        });

**Comment by zhangquan** [comment]
merge时失误，将冲突的文件提交了上去， 会发上修复
