### ISSUE TITLE
mobileprovision_UUID.sh no work

### ISSUE THREAD

**Issue by yans67** [weexteam/weex-pack#106]
OSX ：10.11.6
Xcode：8.0
weexpack：0.3.7
I used mobileprovision_UUID.sh to get my provision UUID,but it did not work,here is the wrong message:
`security: failed to decode message: UNKNOWN (-8183(d)
security: problem decoding
Print: Entry, "UUID", Does Not Exist
UUID is:

`

**Comment by exolution** [comment]
./mobileprovision_UUID.sh /path/to/your/cer.mobileprovision

**Comment by 501956430** [comment]
![img_2873](https://cloud.githubusercontent.com/assets/20204491/24451596/0f391d0e-14b2-11e7-8e2a-ec2d6f01448e.JPG)
@yans67 @exolution  配置好证书安装到真机提示异常，默认配置的也是debug模式下运行的，请问你们有没遇到此问题，如何解决的，谢谢？
