### ISSUE TITLE
weexpack vue2.0 debug 显示空白

### ISSUE THREAD

**Issue by 501956430** [weexteam/weex-pack#110]
weex debug vue文件 debug 是空白,we没问题。

 run android 打包运行vue页面可正常运行。

**Comment by JackPu** [comment]
你能贴下你的文件么？

**Comment by 501956430** [comment]
@JackPu  
总结了下刚才使用了debug不同的命令方式产生的不同结果：
1、weex debug src -V -e src/index.we  OK
2、weex debug src -V -e src/foo.vue 空白  
3、weex debug src/foo.vue OK
上面说的属于第二种情况
![image](https://cloud.githubusercontent.com/assets/20204491/24094023/c123f00c-0d91-11e7-9514-a36c9f27a41f.png)

**Comment by JackPu** [comment]
你就这样用就行啦，
weex debug 如果后面跟着目录，就必须带着 -e 指定入口文件，你希望看到的那个文件

如果预览某一个文件，就直接后面跟文件路径就好。

**Comment by 501956430** [comment]
@JackPu 嗯 ，可实际工作中应该会有多个*.we  *.vue文件关联的，那么必须的指定目录下的所有文件，如果是vue那么将是空白，无法呈现实际效果。
