### ISSUE TITLE
weexpack如何配置才能支持vue

### ISSUE THREAD

**Issue by py389172739** [weexteam/weex-pack#117]
新版的weexpack好像已经支持了vue格式，但是需要怎么设置呢？我把src下的index.we文件删除了，然后在src下新建了一个index.vue文件，但是运行到android上vue页面的内容没有生效，显示的是一个Hello World

**Comment by JackPu** [comment]
@py389172739  你贴下你的版本吧？

**Comment by exolution** [comment]
请升级到0.3.13版本
