### ISSUE TITLE
什么时候可以支持VUE版本项目

### ISSUE THREAD

**Issue by ijry** [weexteam/weex-pack#118]
什么时候可以支持VUE版本项目

**Comment by JackPu** [comment]
已经支持了，最新的版本就是支持 vue的你可以通过weex plugin 触发升级

**Comment by ijry** [comment]
weexpack create test 默认生成的项目还是.we旧版本啊

**Comment by JackPu** [comment]
你用weex create  test 试一下。

**Comment by ijry** [comment]
还是.we

**Comment by JackPu** [comment]
@ijry  嗯 默认创建的是 .we 但是 .vue文件的打包也是支持的。

**Comment by Jam1zhu** [comment]
@ijry 可以更新了
