### ISSUE TITLE
weexpack更新后 vue2.0 文件debug调试出现异常

### ISSUE THREAD

**Issue by 501956430** [weexteam/weex-pack#119]
@JackPu 你好
weex debug foo.vue 异常
![default](https://cloud.githubusercontent.com/assets/20204491/24451179/48d85f36-14b0-11e7-9f1f-cedfa5a5096f.png)
安装在真实机和模拟器可以正常访问，windows环境

**Comment by 501956430** [comment]
weex debug foo.vue  报错 SyntaxError: Unexpected keyword 'export'

**Comment by JackPu** [comment]
嗯，你能贴下你的文件，我测试下么？ @501956430

**Comment by 501956430** [comment]
@JackPu 
![default](https://cloud.githubusercontent.com/assets/20204491/24532895/88e950d4-15f6-11e7-9f8a-80c7ab275218.png)
script 语法修改为 
module.exports = {} 就好了 vue的语法不是 module default {} 吗？

**Comment by JackPu** [comment]
module.exports 是 CMD的模块写法，export default {} 是ES6的写法 详见[这里])(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)，最好你能贴下你的package.json 和 webpack配置， 我好看什么原因，

**Comment by 501956430** [comment]
@JackPu package.json 和 webpack配置，烦请看下
![default](https://cloud.githubusercontent.com/assets/20204491/24575216/f01f949e-16d1-11e7-99c8-ea2f35041aaf.png)

![default](https://cloud.githubusercontent.com/assets/20204491/24575218/f853a6d2-16d1-11e7-99e9-cba0866d9f0d.png)
