### ISSUE TITLE
iOS 证书打包出现异常

### ISSUE THREAD

**Issue by 501956430** [weexteam/weex-pack#121]
@JackPu 您好，能否给出一个ios证书打包的配置教程及打包常见问题，不然就不知道如何处理，谢谢了。

![default](https://cloud.githubusercontent.com/assets/20204491/24533028/7f8547d6-15f7-11e7-842f-e2fed418c0de.png)

![img_2874](https://cloud.githubusercontent.com/assets/20204491/24532983/262adcdc-15f7-11e7-9ca1-2a8b1125ddaa.JPG)

 "AppId":"com.weex.test",
  "CodeSign":"Applexxxxxxx",//keychain证书名称
  "Profile":"DKG6-GKJFGKEG-HRT21231",// $ ./mobileprovision_UUID.sh   ios.mobileprovision执行得出

**Comment by yangshengtao** [comment]
1.要搞清楚CodeSign 与  Profile含义，详情可参考 https://developer.apple.com/support/code-signing/

2.weexpack run ios的时候，如果设备选择真机，需要有Apple的证书与mobileprovision，其中mobileprovision需要weexpack提供的mobileprovision_UUID.sh生成UUID，详情可参考README说明
