### ISSUE TITLE
更新weexpack后 weex run android 卡住无法安装到手机

### ISSUE THREAD

**Issue by 501956430** [weexteam/weex-pack#123]
经常性的出现在：install app... 卡死，然后等了很久（10分钟）还是一样，重新执行还是一样。
![default](https://cloud.githubusercontent.com/assets/20204491/24695573/dfdc55be-1a18-11e7-97ea-5b36028e66e8.png)

**Comment by littleseven** [comment]
是否必现呢？有没有至少一次安装成功？
