### ISSUE TITLE
iOS可否像Android一样，可以配置http的WeexBundle

### ISSUE THREAD

**Issue by raistlinzx** [weexteam/weex-pack#124]
Android 现在只需要修改android.config.json中的WeexBundle就可以直接调用远程http的js，比如

```json
{
  "AppName":"WeexApp",
  "AppId":"com.alibaba.weex",
  "SplashText":"Hello\nWeex",
  "WeexBundle":"http://192.168.0.134:8080/dist/main.js"
}
```

iOS现在能实现这个功能吗？

**Comment by JackPu** [comment]
@raistlinzx  你可以直接通过 `weex` 命令来让手机扫码进行远程JS 的加载，详情看 [这里](https://github.com/weexteam/weex-toolkit)

**Comment by raistlinzx** [comment]
@JackPu 不是扫码加载。weexpack的android脚本里现在就可以实现WeexBundle 直接加载远程js，我想这个功能应该也可以在iOS里实现

**Comment by exolution** [comment]
嗯 我明白你的意思 这块确实是ios的不足 我已经给ios的同学提这个需求了~

**Comment by q757571446** [comment]
你可以修改weexpack的源码来完成对config.xml的写入
