### ISSUE TITLE
win10下运行weexpack run web，一直报错

### ISSUE THREAD

**Issue by dotnet123** [weexteam/weex-pack#131]
换了两台电脑都是这样
![111](https://cloud.githubusercontent.com/assets/21954452/25067314/d6f55ae8-2271-11e7-9998-4b7064d06dc0.jpg)

![qq 20170416065415](https://cloud.githubusercontent.com/assets/21954452/25067310/a538657c-2271-11e7-9d71-1e1d14349948.jpg)

**Comment by JackPu** [comment]
@dotnet123 我能看下你的webpack.config.js么？

**Comment by exjava** [comment]
weex run android 也是这个错误。
Module not found: Error: Can't resolve '..srcindex.vue'

**Comment by dotnet123** [comment]
系统生成的，我没有改过
`const pathTo = require('path');
const fs = require('fs-extra');
const webpack = require('webpack');

const entry = {};
const weexEntry = {};
const vueWebTemp = 'temp';
const hasPluginInstalled = fs.existsSync('./web/plugin.js');



function getEntryFileContent(entryPath, vueFilePath) {
  const relativePath = pathTo.relative(pathTo.join(entryPath, '../'), vueFilePath);
  let contents = '';
  if (hasPluginInstalled) {
    const plugindir = pathTo.resolve('./web/plugin.js');
    contents = 'require(\'' + plugindir + '\') \n';
  }
  contents += 'var App = require(\'' + relativePath + '\')\n';
  contents += 'App.el = \'#root\'\n';
  contents += 'new Vue(App)\n';
  return contents;
}

var fileType = '';

function walk(dir) {
  dir = dir || '.';
  const directory = pathTo.join(__dirname, 'src', dir);
  fs.readdirSync(directory)
    .forEach((file) => {
      const fullpath = pathTo.join(directory, file);
      const stat = fs.statSync(fullpath);
      const extname = pathTo.extname(fullpath);
      if (stat.isFile() && extname === '.vue' || extname === '.we') {
        if (!fileType) {
          fileType = extname;
        }
        if (fileType && extname !== fileType) {
          console.log('Error: This is not a good practice when you use ".we" and ".vue" togither!');
        }
        const name = pathTo.join(dir, pathTo.basename(file, extname));
        if (extname === '.vue') {
          const entryFile = pathTo.join(vueWebTemp, dir, pathTo.basename(file, extname) + '.js');
          fs.outputFileSync(pathTo.join(entryFile), getEntryFileContent(entryFile, fullpath));
          
          entry[name] = pathTo.join(__dirname, entryFile) + '?entry=true';
        } 
        weexEntry[name] = fullpath + '?entry=true';
      } else if (stat.isDirectory() && file !== 'build' && file !== 'include') {
        const subdir = pathTo.join(dir, file);
        walk(subdir);
      }
    });
}

walk();
// web need vue-loader
const plugins = [
  new webpack.optimize.UglifyJsPlugin({minimize: true}),
  new webpack.BannerPlugin({
    banner: '// { "framework": ' + (fileType === '.vue' ? '"Vue"' : '"Weex"') + '} \n',
    raw: true,
    exclude: 'Vue'
  })
];
const webConfig = {
  context: pathTo.join(__dirname, ''),
  entry: entry,
  output: {
    path: pathTo.join(__dirname, 'dist'),
    filename: '[name].web.js',
  },
  module: {
    // webpack 2.0 
    rules: [
      {
        test: /\.js$/,
        use: [{
          loader: 'babel-loader'
        }],
        exclude: /node_modules/
      },
      {
        test: /\.vue(\?[^?]+)?$/,
        use: [{
          loader: 'vue-loader'
        }]
      }
    ]
  },
  plugins: plugins
};
const weexConfig = {
  entry: weexEntry,
  output: {
    path: pathTo.join(__dirname, 'dist'),
    filename: '[name].js',
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [{
          loader: 'babel-loader',
        }],
        exclude: /node_modules/
      },
      {
        test: /\.vue(\?[^?]+)?$/,
        use: [{
          loader: 'weex-loader'
        }]
      },
      {
        test: /\.we(\?[^?]+)?$/,
        use: [{
          loader: 'weex-loader'
        }]
      }
    ]
  },
  plugins: plugins,
};

var exports = [webConfig, weexConfig];

if (fileType === '.we') {
  exports = weexConfig;
}
module.exports = exports;
`

**Comment by JackPu** [comment]
@dotnet123 @exjava 已经修复了windows上的问题，你可以自己替换项目的webpack.config.js: https://github.com/weexteam/weexpack-create/blob/master/templates/webpack.config.js 也可以重新卸载安装weexpack都可以。

**Comment by dotnet123** [comment]
还是有问题npm-debug.log内容如下：
 `0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle xxx@1.0.0~prebuild: xxx@1.0.0
6 silly lifecycle xxx@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle xxx@1.0.0~build: xxx@1.0.0
8 verbose lifecycle xxx@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle xxx@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\android\qi\node_modules\.bin;E:\l\Android\sdk\platform-tools;E:\l\Android\sdk\tools;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\Program Files (x86)\VisualSVN\bin;C:\Program Files\Java\jdk1.8.0_111\bin;%GOPAH%\bin;C:\Program Files\TortoiseGit\bin;E:\go\bin;C:\Program Files\Git\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;d:\Program Files (x86)\Microsoft VS Code\bin;E:\apache-maven-3.3.9\bin;C:\Users\admin\AppData\Roaming\npm
10 verbose lifecycle xxx@1.0.0~build: CWD: E:\android\qi
11 silly lifecycle xxx@1.0.0~build: Args: [ '/d /s /c', 'webpack' ]
12 silly lifecycle xxx@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle xxx@1.0.0~build: Failed to exec build script
14 verbose stack Error: xxx@1.0.0 build: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid xxx@1.0.0
16 verbose cwd E:\android\qi
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error xxx@1.0.0 build: `webpack`
22 error Exit status 2
23 error Failed at the xxx@1.0.0 build script 'webpack'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the xxx package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs xxx
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls xxx
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by dotnet123** [comment]
目录结构如下：
![19](https://cloud.githubusercontent.com/assets/21954452/25161931/7aaf388a-24f1-11e7-9e5d-d3ef16bcaafc.png)

**Comment by dotnet123** [comment]
webpack配置文件如下：
[webpack.config.zip](https://github.com/weexteam/weex-pack/files/931649/webpack.config.zip)

**Comment by dotnet123** [comment]
运行如下：
![5](https://cloud.githubusercontent.com/assets/21954452/25162097/b2e145d0-24f2-11e7-860f-e89d04843461.png)

**Comment by JackPu** [comment]
@dotnet123  你那个配置是老版本的， 你可以直接尝试复制替换下https://github.com/weexteam/weexpack-create/blob/master/templates/webpack.config.js

**Comment by dotnet123** [comment]
不好意思，我直接替换的，还是不行。我另外一个同事试的也是不行，是不是win10的版本不一致？
[webpack.config.zip](https://github.com/weexteam/weex-pack/files/931773/webpack.config.zip)

**Comment by dotnet123** [comment]
你们用的是苹果系统可以吗？可以的话，我找个苹果系统去试试。

**Comment by dotnet123** [comment]
这里是我项目的全部打包文件，再麻烦看看了。
![7](https://cloud.githubusercontent.com/assets/21954452/25163615/3943da56-24fe-11e7-82e8-54d9d039efb0.png)

**Comment by dotnet123** [comment]
我电脑系统
![7](https://cloud.githubusercontent.com/assets/21954452/25163623/4f8ffac4-24fe-11e7-856f-7485088100da.png)

**Comment by dotnet123** [comment]
这里是我项目的全部打包文件，不包含node_modules文件夹，再麻烦看看了。
[qi.zip](https://github.com/weexteam/weex-pack/files/931827/qi.zip)

**Comment by JackPu** [comment]
@dotnet123  你现在报什么错误？

**Comment by dotnet123** [comment]
无论怎么弄就是启动不起来，8080端口也没有被占用
![886](https://cloud.githubusercontent.com/assets/21954452/25172511/e4cdf2ec-2523-11e7-874e-b0e604137cad.png)

**Comment by dotnet123** [comment]
你可以用我之前提供的源码包在win10上面试下吗？谢谢

**Comment by JackPu** [comment]
@dotnet123  你给个QQ我帮你测试下？

**Comment by dotnet123** [comment]
275169263，谢谢

**Comment by yigo3000** [comment]
请问这个问题解决了吗？我在win7上也打不开页面。

**Comment by JackPu** [comment]
@yigo3000 这个问题已经修复了

**Comment by chunge0328** [comment]
![image](https://cloud.githubusercontent.com/assets/6309807/26032700/08c7405c-38cc-11e7-9780-7c963091fa43.png)
![image](https://cloud.githubusercontent.com/assets/6309807/26032704/1d75cd70-38cc-11e7-8232-e6a2bd85df47.png)
win10下，按照步骤还是不行

**Comment by alex1226** [comment]
碰到同样的问题
