### ISSUE TITLE
weexpack run ios 出错

### ISSUE THREAD

**Issue by necfol** [weexteam/weex-pack#133]
node: v7.4.0
weexpack: 0.4.0
macos: 10.12.4
xcode:Version 8.1
错误信息：ATSDK/ATManager.h  file not found
<img width="483" alt="2017-04-17 11 42 57" src="https://cloud.githubusercontent.com/assets/8786120/25078215/7e5dcd28-2363-11e7-9b57-6c6059e6425c.png">

**Comment by 766** [comment]
把这个库还有相关的东西给注了 然后在编译，历经千辛万苦 历时2天  终于让我编译成功了

**Comment by necfol** [comment]
@766 是这个ATSDK 没有正确引入进来么，注释了之后编译不会出问题么？

**Comment by cades** [comment]
遇到同樣的問題. 把 `platforms/ios/Podfile` 中

`pod 'ATSDK-Weex', '0.0.1'`

改成

`pod 'ATSDK', '0.0.1'`

就可以編譯了

**Comment by mbokil** [comment]
`pod 'ATSDK', '0.0.1'`

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/markbokil/dev/weex/funky/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Weexplugin.build/Objects-normal/i386/WeexPluginManager.o /Users/markbokil/dev/weex/funky/platforms/ios/Weexplugin/Weexplugin/Source/WeexPlugin/WeexPluginManager.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by yipcma** [comment]
Weex is still magic to me....amazing, yet not understood...

**Comment by deot** [comment]
I solve it by reinstall `cocoapods`,`sudo gem install cocoapods`.
But I have another problem.
## Environment

* `weex -v`:  v1.1.0-beta.5
* weexpack : v0.4.7-beta.11
*  weex-builder : v0.2.13-beta.2
* weex-devtool : v0.3.2-beta.7
* weex-previewer : v1.3.13-beta.5
* `node -v`: 8.3.0
* `npm -v`: 5.4.1
1. Operating system: Mac OS 10.13
2. Phone/emulator/simulator & version: iPhone 7  & iOS 11

## Error

```
Analyzing dependencies
Fetching podspec for `Weexplugin` from `./Weexplugin/`
Downloading dependencies
Using SDWebImage (3.7.5)
Using SocketRocket (0.4.2)
Installing WXDevtool 0.15.3 (was 0.9.5)
Installing WeexSDK 0.15.1 (was 0.13.0)
Using Weexplugin (0.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.
? Choose one of the following devices iPhone 7 ios: 11.0.1
project is building ...
{
  "devices" :  { .... }
}
ReferenceError: simList is not defined
    at simulatorIsAvailable (/Users/deot/.xtoolkit/node_modules/weexpack/build/run/iOS.js:352:15)
    at _runAppOnSimulator (/Users/deot/.xtoolkit/node_modules/weexpack/build/run/iOS.js:311:8)
    at /Users/deot/.xtoolkit/node_modules/weexpack/build/run/iOS.js:278:7
    at Promise (<anonymous>)
    at runApp (/Users/deot/.xtoolkit/node_modules/weexpack/build/run/iOS.js:276:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by yehot** [comment]
@deot
you  add `let simList` and solve it , but add to which file ???

**Comment by sudeepdk** [comment]
#import <UIKit/UIKit.h>
#import <SRWebSocket.h>
SRWebSocket.h' file not found



#import <WeexSDK/WeexSDK.h>
'WeexSDK/WeexSDK.h' file not found
