### ISSUE TITLE
weexpack build ios后，并未生成ipa

### ISSUE THREAD

**Issue by CaliosD** [weexteam/weex-pack#136]
按照文档说明构建项目，并模拟器运行成功后，运行`weexpack build ios`想构建ipa包。

**本地环境：**
- node：6.10.2
- weexpack：0.4.0
- Xcode：8.3.1

**当前状态：**
- 本地已安装有效证书。
- `ios.config.json`文件内容为：
```
{
    "AppName": "WeexDemo",
    "Version": "0.1",
    "BuildVersion": "0.1.0",
    "AppId": "com.caliosd.WeexPlayground",
    "CodeSign": "iPhone Developer: xxxx (xxxxxxx)",
    "Profile": "Xcode Managed Profile",
    "WeexBundle": "index.js"
}
```
- 输入CodeSign、Profile、AppId后，运行结束，log最终显示“Build success!”。
- 然而并没有“/playground/build/ipa_build/ 目录”，也并没有ipa文件。

**期望结果：**
- 在某个路径下获取ipa。

---

期待指点，谢谢大家。

**Comment by xiaohui-zhangxh** [comment]
最后一行显示的Build succes!是骗你的，翻翻上面的输出，是不是有行代码说"ATSDK/ATManager.h"找不到的错误？

P.S.

BAT的文档难找出一个不垃圾的，Weex出来这么久了，居然跟着官方文档走都不能跑起来一个Native的hello World应用，还指望有多少人能跟随你吗？浪费我的时间。

教你weex init your-project生成一个文档之后，接着说weex platform add android，立马报错。不花点时间，谁知道应该用weex create your-project才能添加Native平台啊！！后面一堆坑，恼怒，放弃了。

**Comment by xiaohui-zhangxh** [comment]
如果是ATSDK错误，参考 #133 ，在Podfile中修改下名字就能解决。如果是“xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH” 错误，根据http://www.wangwenzhuang.com/2017/04/12/ios-xcode8_3-error/ 就能解决。
