### ISSUE TITLE
webpack编译失败

### ISSUE THREAD

**Issue by tentou** [weexteam/weex-pack#137]
我执行的是npm run build
总是报：
ERROR in ./temp?entry=true
Module not found: Error: Can't resolve '..srcindex.vue' in 'E:\weex\demo4\temp'
 @ ./temp?entry=true 1:10-37

**Comment by JackPu** [comment]
@tentou  你重新安装下weexpack 这个问题已经修复了。

**Comment by tentou** [comment]
@JackPu 还是不行····

**Comment by JackPu** [comment]
@tentou 你把webpack.config.js 替换成这个吧https://github.com/weexteam/weexpack-create/blob/master/templates/webpack.config.js

**Comment by tentou** [comment]
@JackPu 复制的但是还是不行，我也觉得是webpack配置的问题，但是没找出哪里配置错了，我重装了webpack还是不行····

**Comment by JackPu** [comment]
你用新的是报什么错误？

**Comment by tentou** [comment]
@JackPu 还是那个错
$ weexpack run android
 => npm install&build
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@^1.9.0 (node_modules\ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN xxx@1.0.0 No repository field.

> xxx@1.0.0 build E:\weex\demo4
> webpack

Hash: 9b78923ea390509b7e6b3af1321aca2bd971a49e
Version: webpack 2.4.1
Child
    Hash: 9b78923ea390509b7e6b
    Time: 1393ms
           Asset       Size  Chunks             Chunk Names
    index.web.js  670 bytes       0  [emitted]  index
       [0] ./temp?entry=true 70 bytes {0} [built]

    ERROR in ./temp?entry=true
    Module not found: Error: Can't resolve '..srcindex.vue' in 'E:\weex\demo4\temp'
     @ ./temp?entry=true 1:10-37
Child
    Hash: 3af1321aca2bd971a49e
    Time: 1381ms
       Asset     Size  Chunks             Chunk Names
    index.js  2.07 kB       0  [emitted]  index
       [0] ./~/weex-vue-loader/lib/script-loader.js!./~/babel-loader/lib!./~/weex-vue-loader/lib/selector.js?type=script&index=0!./src/index.vue 307 bytes {0} [built]
       [1] ./~/weex-vue-loader/lib/style-loader.js!./~/weex-vue-loader/lib/style-rewriter.js?id=data-v-4e62f3dd!./~/weex-vue-loader/lib/selector.js?type=styles&index=0!./src/index.vue 307 bytes {0} [built]
       [2] ./~/weex-vue-loader/lib/template-compiler.js?id=data-v-4e62f3dd!./~/weex-vue-loader/lib/selector.js?type=template&index=0!./src/index.vue 543 bytes {0} [built]
       [3] ./src/index.vue?entry=true 1.69 kB {0} [built]

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! xxx@1.0.0 build: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the xxx@1.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xxx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\weex\demo4\npm-debug.log

**Comment by JackPu** [comment]
最新的已经修复
