### ISSUE TITLE
weexpack run  iOS  报错

### ISSUE THREAD

**Issue by hnny09** [weexteam/weex-pack#138]
localhost:TravelTool Air$ sudo weexpack run ios
npm WARN xxx@1.0.0 No repository field.

> xxx@1.0.0 build /Users/Air/Desktop/Weex/TravelTool
> weex-builder src dist

build failed!
[webpack errors]

Vue packages version mismatch:

- vue@1.0.28
- vue-template-compiler@2.2.6

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 => Will start iOS app
 => pod update
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
? Choose one of the following devices iPhone 6 Plus ios: 9.3
project is building ...
Launching iPhone 6 Plus...
2017-04-20 11:58:17.072 instruments[5983:58260] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Error: Timed out waiting for device to boot: "iPhone 6 Plus (9.3)"
Installing build/Build/Products/Debug-iphonesimulator/WeexDemo.app
No devices are booted.
No devices are booted.
Success!
No devices are booted.

No devices are booted.

ios模拟器reset 几次了没有什么作用，电脑也重启了，还有别的办法吗，给点思路

**Comment by hnny09** [comment]
**localhost:TravelTool Air$ sudo weexpack run ios
npm WARN xxx@1.0.0 No repository field.

> xxx@1.0.0 build /Users/Air/Desktop/Weex/TravelTool
> weex-builder src dist

build failed!
[webpack errors]


Vue packages version mismatch:

- vue@1.0.28
- vue-template-compiler@2.2.6

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.


 => Will start iOS app
 => pod update
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

Usage:

    $ pod COMMAND

      CocoaPods, the Cocoa library package manager.

Commands:

    + cache      Manipulate the CocoaPods cache
    + env        Display pod environment
    + init       Generate a Podfile for the current directory
    + install    Install project dependencies according to versions from a
                 Podfile.lock
    + ipc        Inter-process communication
    + lib        Develop pods
    + list       List pods
    + outdated   Show outdated project dependencies
    + repo       Manage spec-repositories
    + setup      Setup the CocoaPods environment
    + spec       Manage pod specs
    + update     Update outdated project dependencies and create new Podfile.lock

Options:

    --silent     Show nothing
    --version    Show the version of the tool
    --verbose    Show more debugging information
    --no-ansi    Show output without ANSI codes
    --help       Show help banner of specified command
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:47:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
? Choose one of the following devices iPhone 6 Plus ios: 9.3
project is building ...
Launching iPhone 6 Plus...
2017-04-20 11:58:17.072 instruments[5983:58260] WebKit Threading Violation - initial use of WebKit from a secondary thread.
Instruments Error: Timed out waiting for device to boot: "iPhone 6 Plus (9.3)"
Installing build/Build/Products/Debug-iphonesimulator/WeexDemo.app
No devices are booted.
No devices are booted.
Success!
No devices are booted.



No devices are booted.**

**Comment by kennysmoothx** [comment]
Were you able to figure this out?

Experiencing the same problem
