### ISSUE TITLE
weexpack run ios

### ISSUE THREAD

**Issue by mbokil** [weexteam/weex-pack#141]
node: v6.10.2
weexpack: 0.4.0
osx: 10.12.4

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/markbokil/dev/weex/funky/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Weexplugin.build/Objects-normal/x86_64/WeexPluginManager.o /Users/markbokil/dev/weex/funky/platforms/ios/Weexplugin/Weexplugin/Source/WeexPlugin/WeexPluginManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by microzz** [comment]
我也是这个错误，怎么破

**Comment by JeremyWei** [comment]
看一下自己的cocoapods是否安装正确

**Comment by JLraining** [comment]
+1 解决了吗
