### ISSUE TITLE
weexpack run ios报错

### ISSUE THREAD

**Issue by hnny09** [weexteam/weex-pack#142]
ERROR in index.web.js from UglifyJs
Unexpected token punc «(», expected punc «:» [index.web.js:3690,12]

有人知道怎么解决吗

**Comment by hongseokyoon** [comment]
I've got same issue if I tested https://weex.apache.org/references/modules/navigator.html this example.

ERROR in index.js from UglifyJs
    Unexpected token punc «(», expected punc «:» [index.js:85,8]
