### ISSUE TITLE
Cannot add platform

### ISSUE THREAD

**Issue by enricodeleo** [weexteam/weex-pack#143]
Hi everyone!

It seems that something is wrong with `platform add` command. When I try to perform this command npm runs like forever (I tried to wait more than 60 mins befor CTRL+C)

<img width="574" alt="screen shot 2017-04-28 at 12 27 59" src="https://cloud.githubusercontent.com/assets/3534555/25525290/65954a1a-2c0e-11e7-9cb7-63c31665b3cd.png">

**Comment by yipcma** [comment]
I am having the same issue, got stuck with platform add.

**Comment by enricodeleo** [comment]
@yipcma I solved adding the platform with the git https address

**Comment by tralves** [comment]
@enricodeleo Could you please explain exactly what you did? I am having the same issue...

**Comment by yipcma** [comment]
@enricodeleo  what do you mean by git https address?

**Comment by enricodeleo** [comment]
Just execute on your app's root directory :
```bash
weexpack platform add https://github.com/weexteam/weexpack-iOS.git
```

**Comment by tralves** [comment]
@enricodeleo It worked, thanks!

I think the project `weexpack-platform` needs to update this dependency.

**Comment by enricodeleo** [comment]
@tralves you're welcome :) 
Yes, I think the tool should be refreshed but I think the main contributors are busy integrating `weexpack` with `weex`

**Comment by yipcma** [comment]
Thanks @enricodeleo Resources on Weex in English is rather lacking. Are you part of some community? I'd love to catch up and just ping over there if such community exists.
