### ISSUE TITLE
npm run dev实时更新的问题

### ISSUE THREAD

**Issue by bugss** [weexteam/weex-pack#144]
按照官网上面的说明https://weex-project.io/cn/guide/tools/toolkit.html

> 我们先通过
> npm install 安装项目依赖。之后运行 npm run dev 和 npm run serve 开启 watch 模式和静态服务器。

这里的npm run dev 好像不能实时预览吧?  就是index.vue里面的内容改变了,刷新页面web上面的内容并不能实时的更新. 看了半天生成的webpack配置代码,发现必须要npm run build -- --watch 这样才能实时更新.
不太清楚npm run dev ,但是这个命令控制台打印的是
>src/index.vue   -->    dist/index.js
看web/index.html里面的内容,貌似就没有加载过这个文件

应该是因为webpack-dev-server 中配置的entry应该改成webpack-dev-middleware中间件对应的路径,现在web/index.html里面的路径是写固定的,每次代码改变了都需要重新build一下.

后来发现
用weex src --entry src/index.vue 这种方式是可以实时预览的.

我觉得最好还是在文档上面体现一下好,跟着官方文档走还走不通还是有点烦躁的.(只用weex init abc 的项目好像启动之后就报错了,看起来是babel的问题,后来也没有管直接用weexpack重建项目了.
话说weex init abc这种方式生成项目是不是已经被弃了?我大致看了下,webpack还是用的1.x的,weexpack直接是2.x的
)

也可能是写前端的惯性思维,觉得执行个npm run sever 和npm run dev 就可以直接开发了吧,
折腾了一下午,希望对遇到同样问题的人有帮助吧.

**Comment by yooranchen** [comment]
webpack --watch,我这边也是一样无法试试预览.. 请问下,你用的是什么版本的weex呢

**Comment by erha19** [comment]
现在最新的版本已经支持热更新了
