### ISSUE TITLE
weexpack run ios 报错

### ISSUE THREAD

**Issue by geGao123** [weexteam/weex-pack#146]
报错提示：
The following build commands failed:
	CompileC build/Build/Intermediates/WeexDemo.build/Debugiphonesimulator/WeexDemo.build/Objects-normal/i386/AppDelegate.o WeexDemo/AppDelegate.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler(1 failure)

**Comment by kinm** [comment]
+1

**Comment by yipcma** [comment]
same here.

**Comment by yipcma** [comment]
in my case it says library not found for -lSDWebImage

**Comment by SunboyGo** [comment]
+1

**Comment by SunboyGo** [comment]
同样报错：
The following build commands failed:
CompileC build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/AppDelegate.o WeexDemo/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by kinm** [comment]
The solution is here #133

**Comment by yipcma** [comment]
@kinm my issue is with SDWebImage, wonder what's the correct Podfile currently for the different dependencies

**Comment by xiaohui-zhangxh** [comment]
BAT的文档难找出一个不垃圾的，Weex出来这么久了，居然跟着官方文档走都不能跑起来一个Native的hello World应用，还指望有多少人能跟随你吗？浪费我的时间。

教你`weex init your-project`生成一个文档之后，接着说`weex platform add android`，立马报错。不花点时间，谁知道应该用`weex create your-project`才能添加Native平台啊！！后面一堆坑，恼怒，放弃了

**Comment by xiaogaofudao** [comment]
同感，东西是好，可以文档太乱，没有整理归类，东一出西一出，坑太多

**Comment by zacard-orc** [comment]
去年还能搭成功，今年安装文档和楼上一样的失败，浪费了一下午的时间
