### ISSUE TITLE
用weexpack新建一个android项目，index.vue 的内容，出现在 最左侧，然后才突然跑到中间

### ISSUE THREAD

**Issue by xiaogaofudao** [weexteam/weex-pack#147]
用weexpack新建一个android项目，index.vue 的内容，先出现在 最左侧，然后才突然跑到中间
测试手机 魅族 pro6 出现这个问题， 另外一台测试机 oppo r9 没有出现
![s70510-175559](https://cloud.githubusercontent.com/assets/9261849/25893480/8cefc66c-35aa-11e7-934a-caaff0481833.jpg)

**Comment by JackPu** [comment]
你能描述详细些么？没看太懂...

**Comment by xiaogaofudao** [comment]
splash 页面 结束后，进去index.vue 这个页面的时候以下这种情况很大几率会出现上述问题。
在 index.vue 这个页面，点击两次 返回键，程序会退出，然后再打开程序，魅族 pro6 会出现上面的情况，里面的内容先再最左侧出现，然后闪到中间。
其他比如按 home 键回到桌面，再点程序进入显示正常没问题。一键清理内存再打开程序也没问题

**Comment by xiaogaofudao** [comment]
哪位大神遇到过，weexpack 4.0  create 一个 默认项目 然后 android 打包 apk， 传到 魅族 pro6 测试机，出现上述的布局问题，求 weex 项目开发大神 回复

**Comment by xiaogaofudao** [comment]
错了 weexpack 0.4.0

**Comment by xiaogaofudao** [comment]
什么都不修改，官方默认的 项目安卓打包都出现了，还怎么让继续用啊

**Comment by xiaogaofudao** [comment]
求weex 项目组  魅族 pro6 复现此问题。不清楚其他安卓测试机是否还有这个 bug

**Comment by xiaogaofudao** [comment]
目前在官方新建的默认项目 有这个问题，自己写的其他布局，未出现此情况

**Comment by Tancy** [comment]
能说的更详细点吗？

**Comment by xiaogaofudao** [comment]
weexpack create demo 新建一个默认项目， weexpack run android 在 魅族 pro6 跑起来 有此问题，什么都没修改。目前是修改了 布局，还好未出现

**Comment by Tancy** [comment]
你是怎么修改的。
