### ISSUE TITLE
求助个问题，weex vue2 不支持 v-html, 如何通过其他方式实现相同功能

### ISSUE THREAD

**Issue by xiaogaofudao** [weexteam/weex-pack#150]
求助个问题，weex vue2 不支持 v-html, 如何通过其他方式实现相同功能。
iconfont 使用 遇到这个问题

**Comment by xiaogaofudao** [comment]
主要是动态iconfont, 直接 在 text 里面写 &#xe64e;  这种可以，如果放变量里面 就不行了，v-html 不支持。有什么其他方案吗

**Comment by misakuo** [comment]
icon放在变量里需要转义

**Comment by xiaogaofudao** [comment]
只能通过 第三方插件 he 转义了。神烦
