### ISSUE TITLE
weexpack run web

### ISSUE THREAD

**Issue by qiumobai** [weexteam/weex-pack#152]
怎么修改默认8080端口？

**Comment by alex1226** [comment]
同问 感觉这个weexpack create proj 生成的框架坑多。建议在另外的框架上修改：weex-hackernews-master。

**Comment by qiumobai** [comment]
@alex1226 我直接用npm run serve和npm run dev

**Comment by alex1226** [comment]
我在win10上面 npm run dev不成功 没办法弄 也修改不了端口，和Jenkins端口冲突了。

**Comment by qiumobai** [comment]
@alex1226 我的也是win10的啊，是不是你用了es6的，编译失败了

**Comment by alex1226** [comment]
哪里修改es6版本？ 可能是没设置编译选项

**Comment by qiumobai** [comment]
@alex1226 webpack.config
