### ISSUE TITLE
modal 模块的 toast 功能在  魅族 pro6 手机不能工作

### ISSUE THREAD

**Issue by xiaogaofudao** [weexteam/weex-pack#154]
modal 模块的 toast 功能在  魅族 pro6 手机不能工作

**Comment by xiaogaofudao** [comment]
包括官方的 playground toast 例子， 和 自己新建的项目 点击 toast 都没有反应

**Comment by misakuo** [comment]
有一些奇奇怪怪的手机和系统可能会对toast要求特殊的悬浮窗权限

**Comment by xiaogaofudao** [comment]
可以通过修改 Android manifest 配置文件 添加权限 解决么

**Comment by misakuo** [comment]
某些设备比如小米和魅族有全局的toast开关，在用户将开关关闭的情况下所有的toast都不能显示

**Comment by xiaogaofudao** [comment]
是的，用户主动关闭，那没办法，只能自己用其他方式模拟了，如果在 weex 里面都封装好，如果用户没关闭， 用系统自带的，关闭了，用自己实现的toast。这样就好了，现在一看playground 都没反应，估计就这一点会打退一部分人吧

**Comment by xiaogaofudao** [comment]
尝试 weex 很多一部分人的 android 原生开发都比较弱，大部分都是 前端。遇到这种问题很难办 。还有就是模块插件生态还是比较少。想做个完善的 app 没原生能力太难，哪怕你 前端再牛逼也是枉然啊

**Comment by misakuo** [comment]
是这样的，SDK在设计功能的时候肯定是优先遵循标准Android系统的行为，标准以外的行为会通过开放接口提供给开发者自由定制的能力，SDK一定程度上是要避免大而全的
