### ISSUE TITLE
weexpack run ios 'WeexSDK/WeexSDK.h' file not found

### ISSUE THREAD

**Issue by nickming** [weexteam/weex-pack#158]
执行完weexpack run ios报这个错，运行Android没有问题，不知道什么原因
/WeexPlugin/WeexPluginManager.m:11:9: fatal error: 'WeexSDK/WeexSDK.h' file not found
#import <WeexSDK/WeexSDK.h>
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/nickming/Desktop/weex/weexweather/platforms/ios/build/Build/Intermediates/Pods.build/Debug-iphonesimulator/Weexplugin.build/Objects-normal/x86_64/WeexPluginManager.o /Users/nickming/Desktop/weex/weexweather/platforms/ios/Weexplugin/Weexplugin/Source/WeexPlugin/WeexPluginManager.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by nickming** [comment]
未安装cocoapods导致没办法识别这个模块，但是安装完cocoapods又会报错
CompileC build/Build/Intermediates/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/UIViewController+WXDemoNaviBar.o WeexDemo/WeexScanner/UIViewController+WXDemoNaviBar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
不得不说脚手架工程是有bug的，需要手动去podfile里面吧pod 'ATSDK-Weex', '0.0.1'改为pod 'ATSDK', '0.0.1'，问题的结局在[这里#133](https://github.com/weexteam/weex-pack/issues/133)，weex的确是个好东西，就是文档支持太少了，离reactnative还是有一段距离的。

**Comment by sudeepdk** [comment]
The following build commands failed:
	CompileC build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/UIViewController+WXDemoNaviBar.o WeexDemo/WeexScanner/UIViewController+WXDemoNaviBar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
13:36:20 : Error:Error: Command failed: xcodebuild -workspace WeexDemo.xcworkspace -scheme WeexDemo -configuration Debug -destination id=0A2BD198-AAFF-44AD-B57C-0E037EBC02AF -sdk iphonesimulator -derivedDataPath build clean build
2018-03-10 13:35:47.642 xcodebuild[12627:340520]  DTDeviceKit: deviceType from 14105147e0f1c072cae6cc0af3c64f2f8c5bf47b was NULL
** BUILD FAILED **


The following build commands failed:
	CompileC build/Build/Intermediates.noindex/WeexDemo.build/Debug-iphonesimulator/WeexDemo.build/Objects-normal/x86_64/UIViewController+WXDemoNaviBar.o WeexDemo/WeexScanner/UIViewController+WXDemoNaviBar.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at _buildOnSimulator (/Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:328:18)
    at /Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:300:7
    at new Promise (<anonymous>)
    at buildApp (/Users/sudeepiorta/.xtoolkit/node_modules/weexpack/lib/run/ios.js:289:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
