### ISSUE TITLE
用ES6语法时压缩出错

### ISSUE THREAD

**Issue by jasonhe88** [weexteam/weex-pack#159]
我的代码用了ES6语法如箭头函数等，升级weexpack后发现老是提示UglifyJs压缩出错，

后来百度知道只能压缩ES5代码，如是在当前目录下添加 .babelrc 文件， 内容如下:

{"presets":["es2015"]}

把ES6转成ES5代码，压缩成功

不知道有没有其它办法？

**Comment by wensheng** [comment]
这个什么时候能修啊？
在 http://weex.apache.org/guide/ 上的HelloWorld示例是ES6的，用weexpack就不行，出-2013错。
如果把：
```javascript
export default {
    data () {
      return {
        text: 'Hello World.'
      }
    }
  }
```
改成：
```javascript
module.exports = {
    data: {
        text: 'Hello World.'
    }
  }
```
就可以了。

现在很多例子是ES6的，用weexpack都不行，这造成太多的confusion。

还有其他bugs, 能不能跟紧一点，都是好多天都没回复。这么大公司，这么重要的开源项目，多重视点好么？

**Comment by erha19** [comment]
#193
