### ISSUE TITLE
求助，weexpack run web样式渲染异常

### ISSUE THREAD

**Issue by lide1202** [weexteam/weex-pack#160]
通过weexpack run android，在实机和模拟器中，运行APP正常，但在使用weexpack run web时，页面样式渲染异常了，android端有framework做底层渲染，html5端是不是应该也有类似的东西啊？网上关于weex部署html5的资料非常少，期待大神回复。

**Comment by lide1202** [comment]
This has already been solved，it work fine after i load *.web.js in web replace *.js

**Comment by chunge0328** [comment]
大神，是改名字吗

**Comment by lide1202** [comment]
weexpack build web后，会生成两种js，一种是带.web.js的，给浏览器加载的，一种是.js的--给app加载的。
