### ISSUE TITLE
初始化后的项目完全不知道怎么改造，入口文件，router的引入，能不能提供一份详细文档

### ISSUE THREAD

**Issue by sunsunyongjiu** [weexteam/weex-pack#171]
初始化以后完全不知道怎么改造项目，怎么引入vue router等，对新人很不友好

**Comment by alex1226** [comment]
请参考另外的一个项目：weex-hackernews-master

**Comment by sunsunyongjiu** [comment]
我询问了另一个项目，她说他编写的时候还没有你们的工具，是自己搭的，我想知道基于你们编写的框架怎么改造成类似weex-hackernews-master

**Comment by alex1226** [comment]
我不是阿里weexteam的， 是自己发现weex-hackernews-master能用，github上搜搜能找到。
