### ISSUE TITLE
Android project not found !

### ISSUE THREAD

**Issue by mrcaobin** [weexteam/weex-pack#176]
问题说明：
使用weexpack create命令创建命令，进入目录执行npm install，安装包成功后，执行weexpack run android，报错
Android project not found !
按错误提示，weexpack create或weexpack platform add android解决问题。
1.项目本来使用weexpack create创建
2.此时执行weexpack platform add android，会提示android 平台已安装

解决：
删除platforms下面的android，再执行weexpack platform add android

**Comment by panio123** [comment]
有用哦，谢谢！

**Comment by myisliuyuchuan** [comment]
啥么呀 不好使
