### ISSUE TITLE
`weexpack init`时报错：SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by AnnZ** [weexteam/weex-pack#18]
- node_modules/weexpack/src/init/init.js
- node_modules/weexpack/src/utils/index.js

这两个 js 文件报错，应该在第一行加上 `'use strict';`

**Comment by exolution** [comment]
你好，这个原因是你的node版本较低，目前weexpack只支持6.×以上，请先升级一下。我们下一步就会做向下兼容。

**Comment by dodola** [comment]
@AnnZ 我提了一个pr做了这个兼容
