### ISSUE TITLE
如何修改生成的app的名称和图标？

### ISSUE THREAD

**Issue by huzw3** [weexteam/weex-pack#181]
按照教程生成了一个app，但是名称是WEEX，还有图标也是蓝色的weex，想换成自己想要的名称和图标，这个可以在哪里设置吗？
谢谢大神解答。

**Comment by chaiwei** [comment]
have a look at [your weex project folder]\android.config.json or ios.config.json

{
  "AppName":"WeexApp",
  "AppId":"com.alibaba.weex",
  "SplashText":"Hello\nWeex",
  "WeexBundle":"index.js"
}

To change the App Icon, I think you need to go to \platforms\android\app\src\main\res\mipmap-*\icon_launcher.png
