### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by jsasdw1991** [weexteam/weex-pack#182]
![image](https://user-images.githubusercontent.com/6205001/28809174-2e0d5c72-76b4-11e7-88a3-6a8e6f6c70d4.png)

请问一下，有谁碰到过这个问题么。这个脚手架坑好多啊。

**Comment by PerterPon** [comment]
同样有这个问题，先是 ATSDK找不着，把ATSDK-weex改成ATSDK之后，编译是能过了，但是启动的时候又报这个错，简直无语啊，weex坑为啥那么多，照着官方文档连个hello world都跑不起来
