### ISSUE TITLE
local storage/sqlite integrate

### ISSUE THREAD

**Issue by TecladistaProd** [weexteam/weex-pack#188]
have some way to save data on local storage, or/and interaction with sqlite, how i do this? 我的汉语不好

**Comment by misakuo** [comment]
Sure, you can use the `storage` module
http://weex.incubator.apache.org/references/modules/storage.html

**Comment by TecladistaProd** [comment]
when i use this, in android give render error, and give uglify error, i'll try read weex in the node_modules, if have success i close this.
