### ISSUE TITLE
image from computer to app

### ISSUE THREAD

**Issue by TecladistaProd** [weexteam/weex-pack#189]
have a way to run the app with computer image to android without use images from web? for example create in a project folder a folder for photos and images?

**Comment by 2solidtechnologies** [comment]
this has been an issue for a while. I am working on this right now. I am not sure why they haven't responded to this.

**Comment by TecladistaProd** [comment]
when you have an answer please, give me a feedback

**Comment by 2solidtechnologies** [comment]
email me, lets have a chat charles.ongaya@2solid.com
