### ISSUE TITLE
splash screen and app icon

### ISSUE THREAD

**Issue by TecladistaProd** [weexteam/weex-pack#190]
have a way to change the background of splash screen or the animation of the splash screen text ? and have a way to change app icon?

**Comment by chaiwei** [comment]
Hi, not sure if you have found the solution? I am also looking into changing the splash screen text to image. 

For Android

To change splash screen background color: 
[weex project folder]\platforms\android\app\src\main\res\layout\activity_splash.xml

To change app icon:
[weex project folder]\platforms\android\app\src\main\res\mipmap-hdpi\ic_launcher.png
[weex project folder]\platforms\android\app\src\main\res\mipmap-mdpi\ic_launcher.png
[weex project folder]\platforms\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png
[weex project folder]\platforms\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png
[weex project folder]\platforms\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png

**Comment by TecladistaProd** [comment]
thanks for info, but like you, i'm looking into changing to the image or other animation for the text.

**Comment by snurbol** [comment]
To change splash screen animation modify **SplashActivity.java** at _[weex project folder]/platform/android/app/src/main/java/com/weex/app_ (/com/weex/app may be different). It coded in Android native java.
Text on splash screen is in [weex project folder]/android.config.json
Feel free!
