### ISSUE TITLE
weexpack run ios 跑不起来 。

### ISSUE THREAD

**Issue by Likunone** [weexteam/weex-pack#191]
![image](https://user-images.githubusercontent.com/15193414/29768621-932c0fa2-8c19-11e7-93d9-60416efe5fac.png)
![image](https://user-images.githubusercontent.com/15193414/29768644-a77e4bdc-8c19-11e7-93a7-1a9acd8bc663.png)

**Comment by Jam1zhu** [comment]
遇到同样的问题。不熟悉原生开发，望有大神指引

**Comment by Muscot** [comment]
Have same problem, looking for a solution.

**Comment by erha19** [comment]
Update your weexpack by `weex update weexpack`, remove ios floder and run `weex platform add ios` again.

**Comment by mozhijie** [comment]
`sudo gem install cocoapods`
`weex platform add ios`
enjoy!!!

**Comment by jackqqxu** [comment]
ld: library not found for -lSDWebImage

**Comment by GoKu-gaga** [comment]
@erha19 thanks, it work for me
