### ISSUE TITLE
ERROR in index.web.js from UglifyJs

### ISSUE THREAD

**Issue by longer271000** [weexteam/weex-pack#193]
通过weexpack  创建项目后，在执行npm run serve 时报以下错误

ERROR in index.web.js from UglifyJs

Unexpected token: name (urlParts) [index.web.js:3700,4]

已经创建 .babelrc文件 加入{ "presets": ["es2015"] }也不可用

**Comment by fwk1010** [comment]
一样，好像几个月前还可以的

**Comment by setli** [comment]
我也遇到这个问题 
weexpack create 项目名
cnpm install
weexpack run web
也出现
ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3309,4]
ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3311,4]
webpack: Failed to compile.
未找到解决办法

**Comment by erha19** [comment]
升级一下weex-toolkit
`npm i weex-toolkit@latest -g`
再执行`weex update weexpack@latest`就可以解决了，亲测有效

**Comment by fwk1010** [comment]
@erha19 还是不行。
 weexpack -V
  0.4.3

ERROR in index.web.js from UglifyJs
Unexpected token: name (urlParts) [index.web.js:3700,4]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 963 bytes [entry]
         + 1 hidden modules
webpack: Failed to compile

**Comment by Jam1zhu** [comment]
每次升级，会改进一些问题，缺又出现一些新问题。。。

**Comment by yvan0423** [comment]
在webpack配置项里把UglifyJsPlugin注释就行了
`// new webpack.optimize.UglifyJsPlugin({minimize: true}),`

**Comment by erha19** [comment]
Fixed https://github.com/weexteam/weex-toolkit/issues/165

**Comment by SaiyanGuo** [comment]
现在是2017年12月16日，这个问题还没解决？
