### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by HirahKong** [weexteam/weex-pack#196]
4769 verbose stack Error: Error extracting /Users/haorui/.npm/weexpack-create/0.1.9/package.tgz archive: ENOENT: no such file or directory, open '/Users/haorui/.npm/weexpack-create/0.1.9/package.tgz'
4769 verbose stack     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:309:10)
4769 verbose stack     at emitOne (events.js:96:13)
4769 verbose stack     at ReadStream.emit (events.js:188:7)
4769 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:190:14
4769 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:241:16
4769 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
4770 verbose cwd /Users/haorui/projects/weex-pack
4771 error Darwin 16.3.0
4772 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
4773 error node v6.11.3
4774 error npm  v3.10.10
4775 error code EREADFILE
4776 error Error extracting /Users/haorui/.npm/weexpack-create/0.1.9/package.tgz archive: ENOENT: no such file or directory, open '/Users/haorui/.npm/weexpack-create/0.1.9/package.tgz'
4777 error If you need help, you may report this error at:
4777 error     <https://github.com/npm/npm/issues>
4778 verbose exit [ 1, true ]

**Comment by n-sikka** [comment]
+1 on this.. along side this error im also getting an unexpected end of file error.

**Comment by plusice** [comment]
try upgrading npm version to >=5.0.0？
