### ISSUE TITLE
使用weexpack 创建新项目后，web界面无法显示

### ISSUE THREAD

**Issue by vincentwan100** [weexteam/weex-pack#197]
根据官方的命令，创建项目，npm install 后，运行 npm run dev & npm run serve 命令，http://192.168.2.127:8080/ 界面没有报错，但是没有任何信息显示，空白一片！

**Comment by wucuida** [comment]
同样遇到这种情况，不知道怎么解决

**Comment by erha19** [comment]
Please provide your `weex` version.
We recommend that you use`weex-toolkit` and using `weex create` command to create the project, make sure your weex-toolkit is the latest version.

**Comment by wucuida** [comment]
#### weex-toolkit 版本

v1.1.0-beta.1

#### npm 版本

5.4.2

#### node 版本

6.2.1

#### 问题描述
根据官方的命令，创建项目，npm install 后，运行 npm run dev & npm run serve 命令，http://192.168.1.111:8080/ 界面没有报错，但是没有任何信息显示，空白一片！

**Comment by erha19** [comment]
Fixed https://github.com/weexteam/weex-toolkit/issues/165
