### ISSUE TITLE
ReferenceError: simList is not defined (weexpack:v0.4.7-beta.11)

### ISSUE THREAD

**Issue by Becavalier** [weexteam/weex-pack#200]
This error will occur when you run `weex run ios`.  Please define this variable with `var` first before using it.
Node: v8.6.0
Path: ~/.xtoolkit/node_modules/weexpack/build/run/iOS.js

![image](https://user-images.githubusercontent.com/8282020/31980140-337d81c0-b910-11e7-8958-04282f3d50e8.png)

**Comment by hukaibaihu** [comment]
I have the same problem!
