### ISSUE TITLE
EI Caption 10.11.6 无法安装 weexpack

### ISSUE THREAD

**Issue by zannet** [weexteam/weex-pack#21]
npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /usr/local/lib/node_modules/.staging/ios-deploy-1f7f035c
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "weexpack"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /usr/local/lib/node_modules/weexpack/node_modules/ios-deploy/build/Release/ios-deploy
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/weexpack/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/weexpack/node_modules/ios-deploy/build/Release/ios-deploy'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

看提示好像是与ios-deploy有关

**Comment by zannet** [comment]
加了个flag成功了 

sudo npm install -g weexpack --unsafe-perm=true

**Comment by exolution** [comment]
嗯 现在的版本不直接依赖ios-deploy了
且会自动判断如果是EI Caption自动加这个参数
