### ISSUE TITLE
weexpack platform add android 出现Failed to fetch platform android

### ISSUE THREAD

**Issue by zwtgit** [weexteam/weex-pack#213]
Error: Failed to fetch platform android
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: version not found: weexpack-android@6.3.9

**Comment by sharesin** [comment]
me too
![image](https://user-images.githubusercontent.com/5266021/34336850-9fa9bb9c-e995-11e7-9bf7-7417db2fa052.png)

**Comment by kangjunfeng** [comment]
![2017-12-26 5 07 57](https://user-images.githubusercontent.com/27357325/34352759-593652cc-ea5f-11e7-9fbf-bbf553b6c7f2.png)

**Comment by DuKune** [comment]
$ `weexpack platform list`
Installed platforms:
Available platforms:
-android ^6.3.8
$`weex platform add android@6.3.8`
 error: unknown option `--telemetry'

what'swrong？

**Comment by qumuase** [comment]
```
Error: Not Found : egoist
12:37:33 : Error: Failed to fetch platform android@^6.3.8
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Error: Not Found : egoist
```
what's wrong？
