### ISSUE TITLE
run "weex build ios"  error

### ISSUE THREAD

**Issue by humbass** [weexteam/weex-pack#217]
When I run "weex run ios", the iPhone6 simulator starts and displays ok.
when I run "weex build ios", console display：

```
if you want to change build config.please modify ios.config.json
/bin/sh: /Users/dali/.xtoolkit/node_modules/weexpack/build/build/lib/cocoapods-build: No such file or directory
```

 I type command:   sudo find /User/dali -name 'cocoapods-build', console display:
```
dalideiMac:shop123 dali$ sudo find /User/dali -name 'cocoapods-build'
Password:
find: /User/dali: No such file or directory
dalideiMac:shop123 dali$ sudo find / -name 'cocoapods-build'
find: /dev/fd/shop123: No such file or directory
find: /dev/fd/shop123: No such file or directory
/Users/dali/.nvm/versions/node/v8.9.3/lib/node_modules/weexpack/src/build/lib/cocoapods-build
/Users/dali/.xtoolkit/node_modules/weexpack/src/build/lib/cocoapods-build
```

It is clear that the path of 'cocoapods-build'  is wrong

## Your development environment
- weex-toolkit verison (v1.1.0-beta.7)
- platform (Mac)

**Comment by Rockergmail** [comment]
have you solved the problem? I got the same issue.

**Comment by Martin-Mo** [comment]
Same problem here. It's disappointed as i fellow the official docs but could not get the demo project run on ios device.
