### ISSUE TITLE
MACOS，在执行sudo weexpack run android的时候提示找不到$ANDROID_HOME

### ISSUE THREAD

**Issue by ggchxx** [weexteam/weex-pack#22]
项目时 weexpack init 生成的
具体步骤如下
deMacBook-Pro:WeexOne zbmobi$ sudo weexpack run android
npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /Users/zbmobi/ZBMOBI/Vue/WeexOne/node_modules/.staging/ios-deploy-ad3ddfea
npm WARN WeexOne@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.0 (node_modules/ios-deploy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chmod '/Users/zbmobi/ZBMOBI/Vue/WeexOne/node_modules/ios-deploy/build/Release/ios-deploy'

> WeexOne@1.0.0 build /Users/zbmobi/ZBMOBI/Vue/WeexOne
> webpack

Hash: 280fb87f1be38e55bce2
Version: webpack 1.13.3
Time: 893ms
   Asset     Size  Chunks             Chunk Names
index.js  8.78 kB       0  [emitted]  index
    + 4 hidden modules

 => Will start Android app

  Environment variable $ANDROID_HOME not found !

  You should set $ANDROID_HOME first.
  See http://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x
ZbmobideMacBook-Pro:WeexOne zbmobi$ echo $ANDROID_HOME
/Users/zbmobi/DevelopTools/Android/sdk

**Comment by exolution** [comment]
很奇怪 
你加sudo是在root用户下执行的weexpack  是不是你root账户下没有ANDROID_HOME这个环境变量
你sudo echo $ANDROID_HOME 试试

**Comment by ggchxx** [comment]
ZbmobideMacBook-Pro:weexApp zbmobi$ **sudo weexpack run android**

npm WARN lifecycle ios-deploy@1.9.0~preinstall: cannot run in wd %s %s (wd=%s) ios-deploy@1.9.0 ./src/scripts/check_reqs.js && xcodebuild /Users/zbmobi/ZBMOBI/Vue/weexApp/node_modules/.staging/ios-deploy-a04278e4
npm WARN weexApp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.0 (node_modules/ios-deploy):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, chmod '/Users/zbmobi/ZBMOBI/Vue/weexApp/node_modules/ios-deploy/build/Release/ios-deploy'

> weexApp@1.0.0 build /Users/zbmobi/ZBMOBI/Vue/weexApp
> webpack

Hash: 21ac8be4176f1d153377
Version: webpack 1.13.3
Time: 3179ms
                     Asset     Size  Chunks             Chunk Names
   modules/movie-detail.js   215 kB       7  [emitted]  modules/movie-detail
                  index.js  8.79 kB       0  [emitted]  index
   modules/carouse-item.js   183 kB       2  [emitted]  modules/carouse-item
   modules/carouse-list.js   219 kB       3  [emitted]  modules/carouse-list
   modules/essay-detail.js   216 kB       4  [emitted]  modules/essay-detail
           modules/main.js   231 kB       5  [emitted]  modules/main
          modules/movie.js   208 kB       6  [emitted]  modules/movie
                   main.js   191 kB       1  [emitted]  main
        modules/nav-bar.js   185 kB       8  [emitted]  modules/nav-bar
 modules/nav-bar-normal.js   188 kB       9  [emitted]  modules/nav-bar-normal
modules/question-detail.js   212 kB      10  [emitted]  modules/question-detail
           modules/read.js   247 kB      11  [emitted]  modules/read
      modules/read-item.js   186 kB      12  [emitted]  modules/read-item
  modules/serial-detail.js   217 kB      13  [emitted]  modules/serial-detail
  [88] ./src/common/api.js 2.85 kB {1} {3} {4} {5} {6} {7} {10} {11} {13} [built]
    + 141 hidden modules

 => Will start Android app

  **Environment variable $ANDROID_HOME not found !**

  You should set $ANDROID_HOME first.
  See http://stackoverflow.com/questions/19986214/setting-android-home-enviromental-variable-on-mac-os-x
error: protocol fault (couldn't read status): Connection reset by peer
ZbmobideMacBook-Pro:weexApp zbmobi$ **sudo echo $ANDROID_HOME**
/Users/zbmobi/DevelopTools/Android/sdk
ZbmobideMacBook-Pro:weexApp zbmobi$

**Comment by exolution** [comment]
@ggchxx issue 查问题太慢 你把你qq mail我一下 我加你好好调一下这个问题 tanhawk#163.com 
或者加Weex讨论群112304356

**Comment by ggchxx** [comment]
根据作者提示，weexpack检测android_home非常简单 就用的 process.env.ANDROID_HOME，在node中执行，结果sudo 显示未定义，是执行install的权限问题导致的，重新修改权限安装以后，编译通过，
