### ISSUE TITLE
weexpack build android

### ISSUE THREAD

**Issue by kenvies** [weexteam/weex-pack#220]
/usr/local/lib/node_modules/weexpack/bin/weexpack-build.js:45
const build(platform, options) => {
      ^^^^^

SyntaxError: Missing initializer in const declaration
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3

why?

**Comment by kenvies** [comment]
/**
 * Run weex app on the specific platform
 * @param {String} platform
 */
const build (platform, options) => {
  switch (platform) {
    case 'android' : buildAndroid(options); break;
    case 'ios' : buildIOS(options); break;
    case 'web' : buildWeb(options); break;
  }
}

这里写错了啊，const能这样写吗？用下面的方式

const build =  (platform, options) => {
  switch (platform) {
    case 'android' : buildAndroid(options); break;
    case 'ios' : buildIOS(options); break;
    case 'web' : buildWeb(options); break;
  }
}

**Comment by fssgh** [comment]
weexteam的一娃娃写错了代码。。。哈哈！！！请打开/usr/local/lib/node_modules/weexpack/bin/weexpack-build.js文件第45行修改一下，如下：
########原Start##########################
/**
 * Run weex app on the specific platform
 * @param {String} platform
 */
const build(platform, options) => {
  switch (platform) {
    case 'android' : buildAndroid(options); break;
    case 'ios' : buildIOS(options); break;
    case 'web' : buildWeb(options); break;
  }
}
########原end##########################
########修改Start##########################
/**
 * Run weex app on the specific platform
 * @param {String} platform
 */
const build =(platform, options) => {
  switch (platform) {
    case 'android' : buildAndroid(options); break;
    case 'ios' : buildIOS(options); break;
    case 'web' : buildWeb(options); break;
  }
}
########修改END##########################
看到了吗？那娃娃在build后写少了个=号！！！！

**Comment by kolj** [comment]
Hi.
I have the same issue.
Please suggest how to fix it

**Comment by kenvies** [comment]
本来打算提pr的
