### ISSUE TITLE
.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory

### ISSUE THREAD

**Issue by hongmaoxiao** [weexteam/weex-pack#222]
- weex-toolkit: v1.2.7
- weexpack: 1.0.11
- MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
- chrome 63.0.3239.132 (64 bit）

**when  I run **weex run ios**, find this error:**
> /bin/sh: /Users/xxx/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory

**Comment by erha19** [comment]
@hongmaoxiao Fix https://github.com/weexteam/weex-pack/commit/bf2c7562870b8d0a2343c07af7d5a6f7246690e3, you can upgrade your `weexpack` to latest version `v1.0.15`.

**Comment by tuqire** [comment]
I am having the same issue as @hongmaoxiao. 

- weexpack : v1.1.6
- weex-builder : v0.3.14
- weex-previewer : v1.4.6

**Comment by zb1006801184** [comment]
有解决方案不。
