### ISSUE TITLE
weex run ios error

### ISSUE THREAD

**Issue by joneqing** [weexteam/weex-pack#229]
22:24:43 : npm run ios
/bin/sh: /Users/xxx/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory
22:24:43 : Error: Command failed: /Users/xxx/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/ --unsafe-perm=true --allow-root
/bin/sh: /Users/xxx/.xtoolkit/node_modules/weexpack/lib/utils/installIosDeploy.sh/: No such file or directory

info: weex -v
  v1.2.9
 - weexpack : v1.1.6
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

**Comment by kuldeepkeshwar** [comment]
facing the same issue

**Comment by KidneyFlower** [comment]
Hi dude, did you resolved this problem?

**Comment by kuldeepkeshwar** [comment]
nope

**Comment by Cologne88** [comment]
nope

**Comment by KidneyFlower** [comment]
@zb1006801184 目前还没发现解决办法...

**Comment by chenjibin** [comment]
这个是ios-deploy 这个依赖没装好 首先在命令行 输入xcodebuild 如果出现 https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786 这个地址的问题 按照其中采纳的答案进行操作 然后到你自己的weex项目目录下面 执行 npm install 就能成功安装ios-deploy @joneqing

**Comment by KidneyFlower** [comment]
@chenjibin 终于解决了，非常感谢！

**Comment by joneqing** [comment]
@KidneyFlower 配置完成之后run ios 你有没有报pod update command failed这个问题？
