### ISSUE TITLE
MACOS,执行sudo npm install -g weexpack找不到src中的build目录

### ISSUE THREAD

**Issue by ggchxx** [weexteam/weex-pack#23]

**Comment by ggchxx** [comment]
MACOS,执行sudo npm install -g weexpack找不到src中的build目录
/usr/local/lib/node_modules/weexpack/src/  这里面只有run目录 没有 build目录

**Comment by ggchxx** [comment]
。。。我将git项目中的 build目录复制进去了

**Comment by exolution** [comment]
不小心加到npmignore里了 抱歉 0.2.1已修复
