### ISSUE TITLE
weexpack 0.2.0 window下无法打包

### ISSUE THREAD

**Issue by whoiam2007s** [weexteam/weex-pack#24]
weexpack0.2.0不是已经支持window平台了吗，但是window下面没有open命令，run android时报错
{ Error: Command failed: open ./start
这个怎么破

**Comment by MaryWu** [comment]
thanks for your question, will fix it soon...

**Comment by exolution** [comment]
fixed ，just try 0.2.1!

**Comment by MaryWu** [comment]
we'll close this issue for now. if 0.2.1didn't solve your problem, pls feel free to submit another. thanks
