### ISSUE TITLE
  Environment variable $ANDROID_HOME not found !

### ISSUE THREAD

**Issue by cyy2yjp** [weexteam/weex-pack#27]
Environment variable $ANDROID_HOME not found !  webpack run android  的 但是我的环境应该是好的

**Comment by Wangbicong** [comment]
输入指令 `echo $ANDROID_HOME`查看一下路径是否真的存在。

**Comment by Wangbicong** [comment]
不存在就`export ANDROID_HOME="你的路径"`

**Comment by exolution** [comment]
你是不是sudo npm instanll的weexpack 如果是的话就会有这个问题 请卸载 重新不用sudo安装一下

**Comment by MaryWu** [comment]
close this issue for now, if you had further questoin, pls reopen it or create new one. thanks
