### ISSUE TITLE
weexpack run android在Android真机运行不起来

### ISSUE THREAD

**Issue by semmy2010** [weexteam/weex-pack#30]
已经升级到0.2.2了，运行weexpack run android里，没看到具体的报错信息，但APP没在Android机器上跑起来。打包disk目录下也没看到apk文件。
![_20161207132748](https://cloud.githubusercontent.com/assets/4402907/20955825/14f59a9e-bc81-11e6-9db5-d5d3b290d278.png)

**Comment by exolution** [comment]
你好~ 这个错误是adb 报的（error:closed）
请尝试两种方式解决
1、确认的你的android sdk的版本 是不是23 （build tool的版本需要23.0.2）
2、手机如果是android 5.0以下的系统 可能会报这个错 建议尝试换个手机~
3、请关闭手机端的usb调试功能再重新打开 试一下

**Comment by semmy2010** [comment]
@exolution 如果我本地安装了多个Android build tool（有高于23.0.2，有低于23.0.2），那如何指定我用哪个版本来编译？

**Comment by exolution** [comment]
@semmy2010 现在是强制使用23.0.2来编译~还不能指定 你和weex.help里的那个semmy是一个人吧
adb的那个错误我想办法给阉割掉了~你可以试试0.2.3

**Comment by MaryWu** [comment]
close this issue for now, if you had further question, pls reopen it or create new one. thanks

**Comment by cocobear** [comment]
还有一个可能， 有的手机不允许后台安装APK。比如乐视2

> For LeTv Le 2, Go to Settings > Fingerprint & Password > Other Security Options > Install apps in background , Set this options to Yes.
