### ISSUE TITLE
error

### ISSUE THREAD

**Issue by spiritelf** [weexteam/weex-pack#32]
AppId=>com.alibaba.weex
AppName=>WeexApp
SplashText=>Hello
Weex
WeexBundle=>login.js
if you want to change build config.please modify android.config.json
error: closed

**Comment by spiritelf** [comment]
真是各种问题啊。。好多坑

**Comment by spiritelf** [comment]
错误日志哪里看

**Comment by spiritelf** [comment]
error: protocol fault (couldn't read status): Connection reset by peer

**Comment by exolution** [comment]
error: closed 是adb报的错
你的手机操作系统是不是低于android5.0

**Comment by spiritelf** [comment]
必须5.0以上吗？ 有其他曲线方法吗？

**Comment by exolution** [comment]
那我只能把adb reverse功能给阉割掉了(app只能访问本地bundle了)~~你稍等我待会儿发个版好了~

**Comment by exolution** [comment]
@spiritelf 更新weexpack后试一下

**Comment by spiritelf** [comment]
没太明白你说的？可以？

**Comment by spiritelf** [comment]
我在node里更新吗？

**Comment by spiritelf** [comment]
谢谢，可以了，这个是撒回事？
