### ISSUE TITLE
浏览器执行这行代码报错VM1000:150 Uncaught TypeError: Cannot read property 'description' of undefined

### ISSUE THREAD

**Issue by yjjn** [weexteam/weex-pack#33]
var desc = navigator.mimeTypes['application/x-shockwave-flash'].description.toLowerCase();

是我浏览器的原因吗？
还是其他？

**Comment by yjjn** [comment]
谷歌浏览器报错，Safari没问题

**Comment by exolution** [comment]
你这是weex的问题么？首先weex 不支持navigator这种浏览器环境变量的
如果是简单的前端问题你难道不应该对这面这个做保护么？因为他很可能为undefined（报的错也完全是字面意思）
navigator.mimeTypes['application/x-shockwave-flash']

**Comment by yjjn** [comment]
是weex的事例demo。
weepack web 的情况下浏览器报错。
