### ISSUE TITLE
网页能热启动吗？

### ISSUE THREAD

**Issue by yjjn** [weexteam/weex-pack#35]
页面为什么不能自动刷新，每次修改之后还需要重启之后才能刷新内容

**Comment by exolution** [comment]
请描述具体的使用场景或者上下文。
hotreload功能请使用 
weex xxx.we（h5）
weex debug.we（使用手机playground扫码加载）

**Comment by shangcongrong** [comment]
@exolution ，你说的这种hotreload只是单个文件啊，如果多个文件想热更新怎么办呢？

**Comment by exolution** [comment]
@shangcongrong 暂时还不支持~
