### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by xuxubocn** [weexteam/weex-pack#36]
文档太少了，试用是遇到一个低级的错误，不知道要怎么办，求指点一下。

操作如下：

1、程序目录下，运行  weexpack run android
2、报错：Will start Android app 
'adb'     e
'adb'     e

![qq 20161212112304](https://cloud.githubusercontent.com/assets/23071008/21087065/60b48302-c05d-11e6-973b-9c25498e0937.png)

问题是，这是什么错误，如何查看日志，了解具体错误原因？

**Comment by exolution** [comment]
https://github.com/weexteam/weex-pack/wiki 这有详细文档 看起来你的android环境没有安装好
