### ISSUE TITLE
weexpack run web命令不能将src下面的we文件打包到dist下面的js(h5)

### ISSUE THREAD

**Issue by shangcongrong** [weexteam/weex-pack#37]
通过weexpack run web命令，并不能将src下面的we文件转换到dist下面的js文件(h5)，也就是说这个命令没有效果。运行后效果如下，更新的信息也没有：

$ weexpack run web

 => Starting web service
 => server is running
    please open http://localhost:8080/web/index.html

windwos环境下

**Comment by exolution** [comment]
已修复 请更新0.2.4
