### ISSUE TITLE
weexpack run web无法运行

### ISSUE THREAD

**Issue by Donny2g** [weexteam/weex-pack#39]
错误信息如下：
> day1@1.0.0 serve /Users/donny2ghu/Documents/workspace/weexLearn/day1
> serve -p 8080

sh: serve: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v7.2.1
npm ERR! npm  v4.0.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! day1@1.0.0 serve: `serve -p 8080`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the day1@1.0.0 serve script 'serve -p 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the day1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     serve -p 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs day1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls day1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/donny2ghu/Documents/workspace/weexLearn/day1/npm-debug.log
~
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by Donny2g** [comment]
已解决，重新走了遍流程，后把8080端口程序kill掉就好了。不过运行weexpack run web后，没有打包到dist文件。见https://github.com/weexteam/weex-pack/issues/37

**Comment by exolution** [comment]
已修复 请更新0.2.4
