### ISSUE TITLE
weexpack server 窗口 重复出现

### ISSUE THREAD

**Issue by boly95** [weexteam/weex-pack#40]
我的weexpack 版本是 0.2.3
windows 命令行 运行 weexpack run appName 又弹出一个npm窗口，关闭窗口后，重新运行，不再弹出新窗口，但是页面打不开？

**Comment by exolution** [comment]
weexpack 没有weexpack run appName 这种命令吧
weexpack run android/is/web 你是哪个遇到的问题 
另外 你先升级到0.2.4 看是否问题解决了
