### ISSUE TITLE
Error: No android devices found.

### ISSUE THREAD

**Issue by Osub** [weexteam/weex-pack#41]
weexpack  版本0.2.4
```
weexpack run android
.....
WeexBundle=>main.js
if you want to change build config.please modify android.config.json
Error: No android devices found.
```

**Comment by exolution** [comment]
你手机连上了么？请打开usb调试并且选择信任该电脑。

**Comment by Osub** [comment]
不能用模拟机吗？

**Comment by Osub** [comment]
用的小米3真机，开启了usb调试，还是报上面的错误

**Comment by Osub** [comment]
ios通过了，安卓就卡在这里了 ，是缺少什么配置吗？@exolution

**Comment by Lx15** [comment]
我之前也遇到了这个问题，检测不到手机的原因是 在安卓上并未信任手机，你可以看一下这个链接
[Android: Android Studio检测不到手机设备](http://www.hihuyue.com/hihuyue/andoid/android0-android-studio%E6%A3%80%E6%B5%8B%E4%B8%8D%E5%88%B0%E6%89%8B%E6%9C%BA%E8%AE%BE%E5%A4%87)
在设置了这些之后 ，若是还是检测不到手机，你可以在手机上的开发者选项-> 选择调试应用-> 调试应用：weex 然后重新运行 weexpack run android ，这样就可以了。

**Comment by Osub** [comment]
谢谢，已解决@Lx15

**Comment by foreverglory** [comment]
不能用模拟机吗？

**Comment by procoru** [comment]
[我用模拟器](https://dl.dropboxusercontent.com/1/view/iowqkbdvz6d2tav/Apps/Shutter/%C3%90%C2%92%C3%91%C2%8B%C3%90%C2%B4%C3%90%C2%B5%C3%90%C2%BB%C3%90%C2%B5%C3%90%C2%BD%C3%90%C2%B8%C3%90%C2%B5_999%28167%29.png)

**Comment by japrogramer** [comment]
@procoru 
I would like to use the simulator also, Is there a link to how to set this up?

**Comment by turnerguo** [comment]
try open Android Studio -> open a simulator, then start your app.

**Comment by yinxiangming** [comment]
打开ADT启动一个模拟器或者连接一个真机就可以了
