### ISSUE TITLE
'.' 不是内部或外部命令，也不是可运行的程序或批处理文件。

### ISSUE THREAD

**Issue by itzj86** [weexteam/weex-pack#42]
C:\Users\Administrator\Desktop\test\rzhTrip>weexpack build android
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@^1.9.0 (node_modules\
ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deplo
y@1.9.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64
"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN rzhTrip@1.0.0 No repository field.

> rzhTrip@1.0.0 build C:\Users\Administrator\Desktop\test\rzhTrip
> webpack

Hash: fecbe8e909d7fb51d2e8
Version: webpack 1.14.0
Time: 1078ms
   Asset     Size  Chunks             Chunk Names
index.js  9.36 kB       0  [emitted]  index
    + 4 hidden modules

 => Will start Android app
============build config============
AppId=>com.alibaba.weex
AppName=>WeexApp
SplashText=>Hello
Weex
WeexBundle=>index.js
if you want to change build config.please modify android.config.json
 => Building app ...
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by exolution** [comment]
问题已修复 请更新至0.2.5
