### ISSUE TITLE
weexpack run web 

### ISSUE THREAD

**Issue by zhonggedan** [weexteam/weex-pack#43]
`weexpack init test`
`cd test&&npm i`
`weexpack run web`
这样执行完成后：
`http://localhost:8080/web/index.html` 浏览器直接访问，但是访问不了。
错误：
localhost拒绝了链接请求。。。

**Comment by exolution** [comment]
你应该是8080端口有什么东西被占用
先把占用8080端口的程序干掉 再运行试试

**Comment by TotoroChen** [comment]
我也遇到这个问题了，查了端口被chrome占用了，但是这是因为我用chrome打开localhost的缘故吧
