### ISSUE TITLE
0.2.5版本weexpack run android启动的是Weex Playground App，不是自己的工程

### ISSUE THREAD

**Issue by chinafootballyu** [weexteam/weex-pack#48]
win7 64
weexpack init构建了一个自己的工程，没有修改代码，只修改了android.config.json配置
1、android.config.json配置如下
![2](https://cloud.githubusercontent.com/assets/15266646/21835291/ce30b0da-d7f6-11e6-84a2-15c27e3e3be1.png)
2、执行weexpack run android，启动的是Weex Playground App，log了一下weexpack执行的adb命令，截图如下。
![1](https://cloud.githubusercontent.com/assets/15266646/21835253/7e138776-d7f6-11e6-97c3-fc9da35e14d4.png)
3、查看手机，成功安装了工程，但AppName没生效，名字是WEEX。
不知道这两个问题是否BUG？

**Comment by littleseven** [comment]
@exolution 看下不生效原因

**Comment by chinafootballyu** [comment]
没人回答，关了。

**Comment by littleseven** [comment]
@exolution @JackPu app name设置不生效
