### ISSUE TITLE
新文档weexpack 没有这样的命令啊!

### ISSUE THREAD

**Issue by KingWithCA** [weexteam/weex-pack#49]
weexpack create appName
weexpack platform add ios
等都没有这样的命令啊!

**Comment by czyin** [comment]
我这边也有同样的问题：
`$ weexpack platform add ios`
报错：
`Unknown command: platform`

weexpack 更新到最新版本0.2.5，node v7.4.0

**Comment by bekind** [comment]
表示遇到同样的问题，我还以为我的打开方式不对呢，也没人出来解释下么

**Comment by littleseven** [comment]
@bekind @czyin @KingWithCA  请更新最新版本～

**Comment by exolution** [comment]
最新版本0.3.1

**Comment by exolution** [comment]
抱歉weexconf期间我们只发了beta版需要@beta  今天已经正式发布 直接更新至0.3.1即可
