### ISSUE TITLE
beta版maven库连接不上

### ISSUE THREAD

**Issue by hodgevk** [weexteam/weex-pack#51]
0.3.0-beta.2版生成的安卓项目模板里的maven库跟之前版本不一样，好像不能打开，换成老版本的地址就能很快编译程序了。

0.3.0-beta.2:
```
maven { url "http://mvnrepo.alibaba-inc.com/mvn/repository" }
```
之前的：
```
maven { url 'http://repo.baichuan-android.taobao.com/content/groups/BaichuanRepositories/' }
```

**Comment by littleseven** [comment]
已确认 maven { url "http://mvnrepo.alibaba-inc.com/mvn/repository" } 公网不可访问，mark as bug

**Comment by struts2012** [comment]
classpath 'com.android.tools.build:gradle:2.3.2'
classpath 'com.taobao.android:weexplugin-gradle-plugin:1.1.3-SNAPSHOT'
这是1.0.3版生成得android项目里需要的，但是提供的库不能访问，旧版库可以访问但是没有提供gradle2.2.2，也没有weexplugin-gradle-plugin
