### ISSUE TITLE
Error: Could not find directory: /Users/qiupc/.nvm/versions/node/v7.4.0/lib/node_modules/weexpack/node_modules/weexpack-lib/generator/templates

### ISSUE THREAD

**Issue by Vincent2015** [weexteam/weex-pack#54]
Error: Could not find directory: /Users/qiupc/.nvm/versions/node/v7.4.0/lib/node_modules/weexpack/node_modules/weexpack-lib/generator/templates

under the weexpack-lib has no genarator flder. and i  reinstall the weex-pack -g ,but still no.

**Comment by Vincent2015** [comment]
and i try under node6.0 ,has the same error

 at Error: Could not find directory: /Users/qiupc/.nvm/versions/node/v6.0.0/lib/node_modules/weexpack/node_modules/weexpack-lib/generator/templates

**Comment by GreedBell** [comment]
install the 0.2.5 version can fix this

```sh
$ npm install -g weexpack@0.2.5
```
