### ISSUE TITLE
git@gitlab.alibaba-inc.com:alipods/specs.git 无法连接

### ISSUE THREAD

**Issue by fanlinchong** [weexteam/weex-pack#56]
=> Will start iOS app
 => pod update
Update all pods
Cloning spec repo `alibaba-inc-specs` from `git@gitlab.alibaba-inc.com:alipods/specs.git`
[!] Unable to add a source with url `git@gitlab.alibaba-inc.com:alipods/specs.git` named `alibaba-inc-specs`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
-----------------
pod repo add alibaba-inc-specs git@gitlab.alibaba-inc.com:alipods/specs.git
Cloning spec repo `alibaba-inc-specs` from `git@gitlab.alibaba-inc.com:alipods/specs.git`
[!] /usr/local/bin/git clone git@gitlab.alibaba-inc.com:alipods/specs.git alibaba-inc-specs

Cloning into 'alibaba-inc-specs'...
ssh: connect to host gitlab.alibaba-inc.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by bekind** [comment]
更新到最新版后，遇到同样的问题，完全用不了呀

**Comment by forrest23** [comment]
我也遇到同样的问题， 这个  git@gitlab.alibaba-inc.com:alipods/specs.git 地址更本不存在了啊

**Comment by hodgevk** [comment]
podfile里的source不能访问，估计这是个内部gitlab，还是老实用cocoapods/specs吧，慢就慢点
