### ISSUE TITLE
IOS Plugin add有问题

### ISSUE THREAD

**Issue by hodgevk** [weexteam/weex-pack#57]
IOS中plugin add 本地插件之后(例如已经git到本地的gcanvas插件)，xcode编译报错，需要重新pod install，但是执行pod install 会报错：
```
Analyzing dependencies
Fetching podspec for `Weexplugin` from `./Weexplugin/`
[!] Unable to find a specification for `GCanvas` depended upon by `Weexplugin`
```
顺便问句，什么时候可以plugin add market的插件啊？现在执行plugin add会报market error，add本地插件倒是可以的。

**Comment by hodgevk** [comment]
好吧，发现是GCanvas的依赖没有，git@gitlab.alibaba-inc.com:alipods/specs.git 这个连不上，改成https://github.com/CocoaPods/Specs.git 了没有找到，晕死。

**Comment by yangshengtao** [comment]
GCanvas没有在https://github.com/CocoaPods/Specs.git发布，weex-chart插件要等到对外开发之后才能使用
