### ISSUE TITLE
感觉在项目的readme中少了个步骤

### ISSUE THREAD

**Issue by MeishanGuo** [weexteam/weex-pack#59]
以ios为例：

 > 安装ios模版： weexpack platform add ios

 > 在模拟器中运行：weexpack run ios

在上面两步之间，还应该在/platforms/ios 目录下，执行: pod install

**Comment by yangshengtao** [comment]
不需要这个步骤，run ios会自动执行pod操作

**Comment by MeishanGuo** [comment]
谢谢。这样的响应速度和活跃的社区，更让开发者相信weex的未来@MaryWu@yangshengtao。

**Comment by MeishanGuo** [comment]
谢谢。这样的响应速度和活跃的社区，更让开发者相信weex的未来@MaryWu @yangshengtao
