### ISSUE TITLE
IOS项目中没有内置ImageLoader handler

### ISSUE THREAD

**Issue by hodgevk** [weexteam/weex-pack#60]
IOS中没有内置ImageLoader，而安卓中内置了image的adapter，所以会导致demo跑不起来。感觉ios的项目模板比安卓的不够精致和上心。🙄

**Comment by yangshengtao** [comment]
iOS工程是空的壳子，不提供内置的扩展，一是为了减小包大小，二是为了不提供冗余代码，ImageLoader是通过plugin add自定义添加的，ImageLoader可以通过插件市场去查找

**Comment by hodgevk** [comment]
好吧。谢谢
