### ISSUE TITLE
weex-toolkit weexpack创建的项目有什么不同吗？

### ISSUE THREAD

**Issue by kingyang** [weexteam/weex-pack#62]
如题?
weex-toolkit的用法:
```
Usage: weex <foo/bar/we_file_or_dir_path>  [options]
Usage: weex init [projectName]

选项：
  --port    http listening port number ,default is 8081           [默认值: 8081]
  --wsport  websocket listening port number ,default is 8082      [默认值: 8082]

Usage:weex <command>

where <command> is one of:

       debug               start weex debugger
       compile             compile we/vue file
       run                 run your project

weex <command> --help      help on <command> 
```

而 weexpack功能更细化
```
weexpack 所提供的命令大致可分为三组，分别是：

打包命令

weexpack create — 创建 weex 工程项目。
weexpack platform add/remove — 安装／移除 weex 应用模版，默认模版支持 weex bundle 调试和插件机制。
weexpack platform list — 查看已安装的平台模版及版本。
weexpack platform run - 打包应用并安装到设备运行。
插件使用者命令

weexpack plugin add/remove — 安装／移除 weex 插件，支持从本地、GitHub 或者 weex 应用市场安装插件。

weexpack plugin list — 查看已安装的插件及版本。

插件开发者命令

weexpack plugin create - 生成weex插件模版，主要是配置文件和必需的目录。
weexpack plugin publish - 发布插件到weex插件市场。
```
weexpack命令更人性化,但缺少调试命令,越看越迷茫?求点明:
1.两个创建的项目有何区别?
2.两个项目都要用,只是创建项目的命令重复了?

**Comment by jasonhe88** [comment]
同问， 很希望在这些方向性纲领性问题上有明确的说明

**Comment by alex-zhang** [comment]
把两个工具 合并吧

**Comment by jasonhe88** [comment]
发现在webpack.config.js里支持了Vue, 写一个简单的vue文件， 能够编译成功，但是在ios里运行不了，因为还是语法的问题， 把@click改成onclick就可以运行， 看来vue支持还是有问题

你外， 把每个文件都当成入口文件的做法很好用，和ios或android集成时每个js文件对应一个页面

**Comment by xujingbao** [comment]
weexpack和 ionic cli 挺像的 →_→

**Comment by JackPu** [comment]
weexpack是一个集成工程化的命令行工具，它今后扩展的功能会更多，比如对于插件模块的支持，对于不同平台的支持。

而weex-toolkit更加自由一点，但是功能也仅仅局限于对weex或者vue页面的开发相关的辅助上。

@alex-zhang  我们后期会也有策略让weex-toolkit进行功能的扩展，让它具备更加复杂的功能。

**Comment by kingyang** [comment]
@alex-zhang  支持,建议把两个项目合并,要不**别长得太像**哈

**Comment by alex-zhang** [comment]
@JackPu weex-toolkit (内嵌build流程) 的 js bundle 的流程和 weexpack 不一样吧。 这样不会有问题么？ 建议统一（且把build的流程完全交给开发者）

npm 上面 有个 ‘weex-cli ’ 建议联系作者， 用这个名字。

还有 最好像 vue-cli 那样 支持 模版工程 方式的创建。  cli 不要定死流程和方式。

**Comment by exolution** [comment]
现在已经把weexpack加入weex-toolkit工具集里。
至于初始化的模板的差异我们下一步会抹平

**Comment by ruixiu** [comment]
还有一个问题：全局安装了weexpack，使用weex platform add ios的时候还是会提示下载安装weexpack
