### ISSUE TITLE
yarn global add weex-pack

### ISSUE THREAD

**Issue by alex-zhang** [weexteam/weex-pack#63]
我们现在 基本已经 切换到 yarn 了，但是这样安装了之后，会有问题

**Comment by JackPu** [comment]
@alex-zhang  请问安装后有什么问题？

**Comment by JackPu** [comment]
建议试下`yarn global add weexpack` weex-pack的包不再维护。

**Comment by alex-zhang** [comment]
node -v
v7.4.0
yarn -v                                                                                                           
yarn install v0.19.1

错误 ： weexpack-create(1) does not exist, try --help

和这个 issue 一样 https://github.com/weexteam/weex-pack/issues/67

**Comment by alex-zhang** [comment]
yarn 和 npm 对于 bin 里面的处理方式是不是不一样啊？

**Comment by exolution** [comment]
yarn严重不兼容npm
碍于一些特性 所以暂时无法支持yarn

**Comment by exolution** [comment]
另外说句题外话 yarn.lock的功能 npm shrinkwrap 也能做到 不知yarn优势何在
