### ISSUE TITLE
怎么开始新的项目？

### ISSUE THREAD

**Issue by alex-zhang** [weexteam/weex-pack#65]
1. create project in git repo
2. clone to local
3. how to do my first step here ???????????????   
    + cd $YOUR_PROJECT_DIR && weexpack create .   
    ```Invalid project name: .```
    + weexpack create $YOUR_PROJECT_DIR
   ```Error: Path already exists and is not empty: /Users/alex/Projects/${YOUR_PROJECT_DIR}```

建议 不要限制目录存在了吧， 最多加个确认， 且可以支持不用用户确认。 感谢！！

**Comment by MaryWu** [comment]
weexpack create命令后面接的是项目名称，执行该命令之后会在当前目录产生和项目名称一致的子目录。详细说明见readme文件。

**Comment by alex-zhang** [comment]
@MaryWu 支持当前目录 ‘.’ 不是更友好点么。  

而且有些情苦是先已经有git 项目了然后再 weexpack create。 而不是先  weexpack create 再$you_project_name 再添加git repo 啊
