### ISSUE TITLE
weexpack not support init a vue project?

### ISSUE THREAD

**Issue by xujingbao** [weexteam/weex-pack#69]
use weexpack create app

├── README.md
├── android.config.json
├── config.xml
├── hooks
│   └── README.md
├── ios.config.json
├── package.json
├── platforms
├── plugins
│   └── README.md
├── src
**│   └── index.we**
├── start
├── start.bat
├── tools
│   └── webpack.config.plugin.js
├── web
│   ├── index.html
│   ├── index.js
│   └── js
│       └── init.js
└── webpack.config.js

7 directories, 15 files

**Comment by segatecm** [comment]
是啊，为什么weexpack还在用we文件啊。

**Comment by zhangquan** [comment]
vue 的支持， 已经在我们的开发计划之中，未来将会支持

**Comment by csvwolf** [comment]
你好，可以试试 <https://github.com/csvwolf/weex-vue-starter-kit>

**Comment by xujingbao** [comment]
@csvwolf 这是一个生成好的工程模板，基于vue，支持weexpack和weextoolkit，而不是一个脚手架，是这样么？

**Comment by hodgevk** [comment]
@zhangquan 计划什么时候推出啊？

**Comment by littleseven** [comment]
@hodgevk 在weex sdk推出sdk0.10稳定版后跟进

**Comment by hodgevk** [comment]
@littleseven 那weex的0.10版本什么时候发布啊？^_^

**Comment by hodgevk** [comment]
0.10.0推出已经有段日子了，什么时候支持vue啊

**Comment by JackPu** [comment]
@hodgevk  嘻嘻，已经完成开发了，在测试中了。如果要体验可以去分支上vue2.0分支上做下小白鼠🐁。

**Comment by exolution** [comment]
0.3.12已经支持~
