### ISSUE TITLE
Waiting for weex plugin (native extend) develop document

### ISSUE THREAD

**Issue by Acathur** [weexteam/weex-pack#70]

**Comment by JackPu** [comment]
@Acathur 
iOS扩展文档
[weex-extend-iOS](https://weex-project.io/cn/references/advanced/extend-to-ios.html) 
andoid扩展文档
[weex-extend-android](https://weex-project.io/cn/references/advanced/extend-to-android.html)

参考项目实现: https://github.com/weex-plugins/weex-plugin-amap

**Comment by Acathur** [comment]
@JackPu 文档没说怎么打包成plugin啊，我看看amap实现

**Comment by MaryWu** [comment]
谢谢，plugin开发文档正在整理中，很快会出来
