### ISSUE TITLE
动态注册 权限申请结果的广播

### ISSUE THREAD

**Issue by jinzunyue** [weexteam/weex-pack#73]
IntentFilter intentFilter = new IntentFilter();
intentFilter.addAction("requestPermission");
intentFilter.addCategory(Intent.CATEGORY_DEFAULT);
mWXSDKInstance.getContext().registerReceiver(new Broadcast(), intentFilter)
为什么接受不到WXPageActivity#onRequestPermissionsResult中发出的广播呢？在WXPageActivity中debug确定广播已经发出

**Comment by misakuo** [comment]
权限申请相关的解决方案可以参照 https://github.com/weex-plugins/weex-permissions/blob/master/android/PermissionsModule.java
