### ISSUE TITLE
Weex plugin 开发问题：Native API模块使用JS进行二次封装

### ISSUE THREAD

**Issue by Acathur** [weexteam/weex-pack#74]
目前采用方案：
1. 创建npm module
2. 使用__weex_define__引入模块WeexAPI模块
3. 在.we文件中引用npm模块

请问是否有办法直接打包到plugin项目中？

**Comment by JackPu** [comment]
你只需要在你的JS目录下写业务代码就好，weexpack plugin add 命令的流程会自动将JS目录的内容按照npm 模块的形式存放到node_module下。你可以参考[weex-chart](https://github.com/weex-plugins/weex-chart)的实现。
不过要求你的JS目录按照标准的npm模块写法，需要指定入口文件并且遵守CMD模块规范。
