### ISSUE TITLE
iOS调用[WXSDKEngine initSDKEnvironment]拼写错误

### ISSUE THREAD

**Issue by ijry** [weexteam/weex-pack#76]
iOS调用[WXSDKEngine initSDKEnvironment]拼写错误改成[WXSDKEngine initSDKEnviroment]就正常了。

**Comment by yangshengtao** [comment]
最新版本WeexSDK中这个initSDKEnviroment接口已经deprecated，替换为了initSDKEnvironment，你需要升级一下WeexSDK
