### ISSUE TITLE
weexpack run android 提示timed out怎么解决？

### ISSUE THREAD

**Issue by tangjion** [weexteam/weex-pack#77]
在打包安装的过程中：weexpack run android
提示java.net.ConnectException:Operation timed out (Connection timed out)怎么办？一直连接超时！

**Comment by littleseven** [comment]
信息较少，是不是gradle下载失败呢？国内同学常会碰到

**Comment by JackPu** [comment]
@tangjion  你能够提供下截图么，我也遇见过一直说timeout的问题。

**Comment by exolution** [comment]
建议翻墙后尝试
