### ISSUE TITLE
怎么加载本地图片

### ISSUE THREAD

**Issue by Jam1zhu** [weexteam/weex-pack#83]
图标和默认图想存在本地，weexpack编译之后本地图片不显示

哪路大神给个好的实现思路？

**Comment by boborz** [comment]
<template>
  <div class="container">
      <image src="http://ata2-img.cn-hangzhou.img-pub.aliyun-inc.com/7d42775b8f0d0c86589082dc9ee179c2.png" class="bannar-image"></image>
      <text class="message">{{ message }}</text>
      <text class="quotes">{{ quotes }}</text>    
  </div>
</template>
你把这里面的图片路径改成file://本地路径
加载网络图片其实使用下面的函数SDwebImage实现的
- (id<WXImageOperationProtocol>)downloadImageWithURL:(NSString *)url imageFrame:(CGRect)imageFrame userInfo:(NSDictionary *)userInfo completed:(void(^)(UIImage *image,  NSError *error, BOOL finished))completedBlock
{
    if ([url hasPrefix:@"//"]) {
        url = [@"http:" stringByAppendingString:url];
    }
    return (id<WXImageOperationProtocol>)[[SDWebImageManager sharedManager] downloadImageWithURL:[NSURL URLWithString:url] options:0 progress:^(NSInteger receivedSize, NSInteger expectedSize) {
        
    } completed:^(UIImage *image, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {
        if (completedBlock) {
            completedBlock(image, error, finished);
        }
    }];
}
你可以在里面添加一个if判断
if ([url hasPrefix:@"file://"]) 
这样就去本地去找资源 
然后记得返回一个实现(id<WXImageOperationProtocol>)的空对象就可以了，cancel函数为空函数。
