### ISSUE TITLE
weex如何根据数据动态添加视图

### ISSUE THREAD

**Issue by bekind** [weexteam/weex-pack#86]
如何通过后台返的数据动态创建标签或者组件，而不是在template中提前写好然后再绑定数据源

**Comment by JackPu** [comment]
可以的，你可以通过自组件的形式，用接口请求完后，讲自组件渲染出来，参考: https://github.com/weex-plugins/weex-amap/blob/search-feature/demos/index.we

**Comment by bekind** [comment]
我没看错的话，这个例子是提前在template中写好的<example-list items="{{items}}"></example-list>，然后绑定items数据源的。我想要的是，事先已经写好了多个组件，根据后台返回的数据来加载这些组件，这些组件是混合乱序的，可能有也可能没有，完全由后台配置，所以需要根据数据源动态初始化这些组件，而不是在template中事先写好。不知道这样说是否清楚

**Comment by JackPu** [comment]
像这样的逻辑如果你是在当前页面进行渲染的话，所有的逻辑都是在
`<template></template>`去实现的，这个取决于你的逻辑，不能避免说因为你这次数据里不需要渲染这个组件就不写，这些完全取决于你自己逻辑控制。
