### ISSUE TITLE
如何给一个app签名

### ISSUE THREAD

**Issue by coolicer** [weexteam/weex-pack#89]
照着教程跑了一个hello world，可是只能跑到虚拟机上，还有就是连USB的时候能build到手机，怎么build一个签名的app啊，前端不是很懂这些。

**Comment by py389172739** [comment]
@coolicer  
用AndroidStudio打开工程目录下的platforms里面的android项目，导入项目的教程：
http://jingyan.baidu.com/article/14bd256e46a974bb6d261298.html
注意：打开后把AS左侧的目录树切换到Project模式下，看app目录上是否有个小手机的图标，只有app目录上有小手机图标才算编译成功，然后再进行一下步
切换目录树模式的教程:
http://www.open-open.com/lib/view/open1436323668817.html
编译没问题之后，再看这个教程，教你怎么给app签名：
http://www.cnblogs.com/sows/p/5678534.html

**Comment by py389172739** [comment]
@coolicer 
AndroidStudio是安卓的开发工具，需要翻墙

**Comment by coolicer** [comment]
@py389172739 我签名了打开说没权限。

**Comment by py389172739** [comment]
@coolicer 哪一步提示没权限？发截图

**Comment by coolicer** [comment]
@py389172739 安装的时候提示我这个app没有申请任何权限，然后安装完成就说没有权限，打开不了。再点安装，就是覆盖了。是不是没有生成快捷方式而已

**Comment by coolicer** [comment]
![image](https://cloud.githubusercontent.com/assets/811078/23398363/2fdb5b9a-fdd7-11e6-852a-f76bfd2a1da1.png)
![image](https://cloud.githubusercontent.com/assets/811078/23398366/32f012c6-fdd7-11e6-8e52-a45eede826b3.png)

**Comment by coolicer** [comment]
我重新弄了一下，安装失败。
![image](https://cloud.githubusercontent.com/assets/811078/23400040/81a8a51c-fddd-11e6-907e-a20adcc3c126.png)

**Comment by py389172739** [comment]
@coolicer  我试了一下，可以给app签名，安装使用也没问题的，安装前你需要先把之前的weex应用卸载了，不然安装不了，你用创建新的签名文件再试试

**Comment by coolicer** [comment]
@py389172739 你也是weexpack run android这样编译出来再签名的吗？

**Comment by py389172739** [comment]
@coolicer  不太一样，我是用weexpack创建的工程，然后用AndroidStudio打开platforms下的android项目，然后用AndroidStudio编译一下，再创建一个新的签名文件并且生成签名版的apk，打开apk所在的目录，打开cmd窗口，用adb install apk目录   的命令安装到手机上的

**Comment by coolicer** [comment]
@py389172739 原来是我之前没签名，后来签名了导致有问题
