### ISSUE TITLE
用weexpack创建工程后，安装依赖老是失败，求帮助！

### ISSUE THREAD

**Issue by py389172739** [weexteam/weex-pack#90]
我的用途：我想用weexpack创建一个工程，用于android平台的开发，后续想兼容h5，但是我创建工程后，用npm安装依赖的时候老是失败，求帮助，以下是我的操作步骤：
1 . 用weexpack创建了一个工程
    命令：weexpack create weexDemo1
2. 进入到工程目录下
   命令：cd weexDemo1
3. 在工程目录下安装依赖
   命令：npm install

到这一步的时候出现了问题：
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ios-deploy@^1.9.0 (node_modules\ios-deploy):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN vue-loader@10.3.0 requires a peer of css-loader@* but none was installed.
npm WARN vue-loader@10.3.0 requires a peer of vue-template-compiler@^2.0.0 but none was installed.
npm WARN xxx@1.0.0 No repository field.
 
对node.js和npm我是小白，不太明白安装的原理，我尝试过以下解决方案：
方案1.
我之前装过weex-toolkit,以为weex-toolkit与weexpack之间安装的依赖有版本冲突，卸载了weex-toolkit重新创建一个新工程安装依赖还是不行

方案2.
重新更新npm版本
命令：npm install -g npm
再重新创建一个新工程安装依赖还是不行

方案3.
重新卸载了weexpack，重新安装weexpack再重新创建一个新工程安装依赖还是不行

方案4.
自己在工程目录下手动安装css-loader和vue-template-compiler
命令：npm install css-loader   和  npm install vue-template-compiler
还是报错

方案5：
进入到工程的vue-loader目录下，手动安装css-loader和 vue-template-compiler还是报同样的错误

devDependencies 和 peerDependencies中的vue-template-compiler版本好像不一样，这个会不会有影响？

小弟对node.js和npm是小白
请大神帮忙解决下这个安装依赖的问题，多谢！

**Comment by coolicer** [comment]
安卓环境配置了吗？

**Comment by py389172739** [comment]
@coolicer  配置了，我本身是做安卓原生开发的，用的是AndroidStudio，我用weexpack创建工程，然后安装依赖，这一步应该不会用到安卓的环境吧？我的理解应该是依赖安装完成了然后在添加安卓平台才会用到安卓的环境

**Comment by coolicer** [comment]
@py389172739 我感觉会有用到吧，不太清楚，教程里也是配置好环境才开始生成项目的。我昨天也跑了一个安卓的hello world

**Comment by py389172739** [comment]
@coolicer  多谢你的回答，我待会再检查下我的android环境，再重现试一下。其实按照
weexpack create appName==> cd appName & npm install ===>weexpack platform add android 的方式我的工程都可以建立起来，我把platform里面的android项目用as打开，是可以跑到手机上的，只是我在写代码的时候发现<script>标签里面的数据加载不起来（图片显示不出来），我怀疑是我的vue-template-compiler没装好导致的，我把我的代码copy后放在
http://dotwe.org/weex/e5191b40a4e95c740b2abfa6f73ea45b
选择vue保存运行图片可以加载出来，选择weex保存运行图片加载不出来，所以我感觉会不会是vue的编译问题，刚好我在npm install安装依赖的时候vue-template-compiler出了问题，感觉可能跟这个安装依赖出问题的可能性很多

@coolicer：
你也是这种方式创建工程的吗？如果你用的是其他方式麻烦告知一声， 我也试试
你看能不能帮忙把我的代码放在你搭建好的项目里跑一下试一下，看图片是否能加载出来？

以下是我测试的源代码：
<template>
    <div>
		<slider class="slider" interval="3000" auto-play="true">
			<div class="frame" v-for="img in imageList">
				<image class="image" resize="cover" :src="img.src"></image>
			</div>
		</slider>
    </div>
</template>
<style scoped>
	.image{
		width: 700px;
		height: 700px;
	}
	.slider{
		margin-top: 25px;
		margin-left:25px;
		width: 700px;
		height: 700px;
		border-width: 2px;
		border-style: solid;
		border-color: #41B883;
	}
	.frame{
		width:700px;
		height: 700px;
		position: relative;
	}
</style>
<script>
	export default{
		data(){
			return{
				imageList:[
					{ src: 'https://gd2.alicdn.com/bao/uploaded/i2/T14H1LFwBcXXXXXXXX_!!0-item_pic.jpg'},
					{ src: 'https://gd1.alicdn.com/bao/uploaded/i1/TB1PXJCJFXXXXciXFXXXXXXXXXX_!!0-item_pic.jpg'},
					{ src: 'https://gd3.alicdn.com/bao/uploaded/i3/TB1x6hYLXXXXXazXVXXXXXXXXXX_!!0-item_pic.jpg'}
				]
			}
		}
	}
</script>

**Comment by coolicer** [comment]
@py389172739 我也是weexpack create appName==> cd appName & npm install ===>weexpack platform add android 这样建项目的。帮你跑一下你的代码？

**Comment by py389172739** [comment]
@coolicer  挺奇怪的，这是什么原因呢？难道vue.js需要单独引入吗？，应该不会啊，你看能不能再创建个新工程，看你npm install 的时候会不会也报什么错误(包括warn)

**Comment by coolicer** [comment]
@py389172739 我感觉是slider这个插件的问题

**Comment by py389172739** [comment]
@coolicer 恩，也有可能，待会我换成其他的控件试试

**Comment by coolicer** [comment]
@py389172739 因为我单独用<img src'"xxx"></img>这样可以显示图片，没有找到有例子用这个模块的。你有没有找到

**Comment by coolicer** [comment]
@py389172739 我跑出图片来了
`
<div repeat="{{imageList}}" class="frame">
        <image src="{{src}}" class="image" resize="cover"></image>
 </div>
`

**Comment by py389172739** [comment]
@coolicer 非常感谢！看来真的是slider控件的问题

**Comment by coolicer** [comment]
@py389172739 你知道怎么加签名吗，我的issue在下面https://github.com/weexteam/weex-pack/issues/89

**Comment by exolution** [comment]
npm warn全部都是可忽略的
