### ISSUE TITLE
ios build cannot find babel presets es2015

### ISSUE THREAD

**Issue by mbokil** [weexteam/weex-pack#96]
I had a problem running the ios build. I initially received the error "Module build failed: Error: Couldn't find preset "es2015" relative to directory." I corrected this issue by editing package.json and adding the babel presets manually. I tested this on 2 new install and the only way to build on ios was to add the preset to package.json

`
"babel": {
      "presets": [
        "es2015"
      ]
    }
`

**Comment by exolution** [comment]
if you want to use es2015
please 
npm install babel-preset-es2015
npm install babel-plugin-transform-runtime
or other babel lib you need
