### ISSUE TITLE
images fail to appear with weexpack run ios

### ISSUE THREAD

**Issue by mbokil** [weexteam/weex-pack#97]
Simple images fail to appear when I execute weeexpack run ios. The image dimensions appear on the iphone simulator but the image is missing. 

`<image style="width:600px;height:150px" src="https://weex-project.io/img/weex_logo_blue@3x.png"></image>`

**Comment by JackPu** [comment]
@mbokil  if you use `.we` file, you should try below:
``` js   
style="width:600;height:150;"
```

In fact, if you use `.vue` file， your syntax is correct.
