### ISSUE TITLE
weexpack platform add ios error

### ISSUE THREAD

**Issue by Jerry-ycj** [weexteam/weex-pack#99]
按文档搭建demo，运行weexpack platform add ios 出错：
Error: Unexpected token <<

有人知道为什么吗？

**Comment by marsal1212** [comment]
0.3.11 也出现了这个错误，回0.3.4就好了。

**Comment by Jerry-ycj** [comment]
@marsal1212 嗯，可以了，谢谢

**Comment by Gavin-Gong** [comment]
@marsal1212 @Jerry-ycj 0.3.11指的是什么的版本??
